project_id = "sjghitoydzpirpqjules"

[functions.import-nominees]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.nrc]
verify_jwt = false

[functions.voting]
verify_jwt = false

[functions.certificates]
verify_jwt = false

[functions.season]
verify_jwt = false

[functions.stage]
verify_jwt = false

[functions.jury]
verify_jwt = false

[functions.payments]
verify_jwt = false

[functions.content]
verify_jwt = false

[functions.uploads]
verify_jwt = false

[functions.wallet]
verify_jwt = false

[functions.dashboard]
verify_jwt = false

[functions.referrals]
verify_jwt = false

[functions.olc]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.nominations]
verify_jwt = false

[functions.verify]
verify_jwt = false