// AUTO-GENERATED by /tmp/build_icons.py from AFRICAN_ICON_PICTURE_FOLDER zip
// Maps nominee slug (and unsuffixed name-slug fallback) to portrait URL.

export const ICON_IMAGE_MANIFEST: Record<string, string> = {
  "abdul-samad-rabiu": "/images/africaicons/abdul-samad-rabiu.jpg",
  "abdulrazak-gurnah": "/images/africaicons/abdulrazak-gurnah.jpg",
  "abiola-irele": "/images/africaicons/abiola-irele.png",
  "acha-leke": "/images/africaicons/acha-leke-tech.jpg",
  "acha-leke-tech": "/images/africaicons/acha-leke-tech.jpg",
  "achille-mbembe": "/images/africaicons/achille-mbembe.jpg",
  "aigboje-aig-imoukhuede": "/images/africaicons/aigboje-aig-imoukhuede.jpg",
  "akin-adesokan": "/images/africaicons/akin-adesokan.jpg",
  "akinwumi-adesina": "/images/africaicons/akinwumi-adesina.jpg",
  "ali-partovi": "/images/africaicons/ali-partovi.jpg",
  "amartya-sen": "/images/africaicons/amartya-sen.jpg",
  "amina-mama": "/images/africaicons/amina-mama.jpg",
  "amina-mohammed": "/images/africaicons/amina-mohammed-curriculum.jpg",
  "amina-mohammed-curriculum": "/images/africaicons/amina-mohammed-curriculum.jpg",
  "andrew-alli": "/images/africaicons/andrew-alli.jpg",
  "antonio-guterres": "/images/africaicons/antonio-guterres-curriculum.png",
  "antonio-guterres-curriculum": "/images/africaicons/antonio-guterres-curriculum.png",
  "ashish-thakkar": "/images/africaicons/ashish-thakkar.jpg",
  "ashish-thakkar-diaspora": "/images/africaicons/ashish-thakkar-diaspora.jpg",
  "ato-quayson": "/images/africaicons/ato-quayson.jpg",
  "audrey-cheng": "/images/africaicons/audrey-cheng-africa.jpg",
  "audrey-cheng-africa": "/images/africaicons/audrey-cheng-africa.jpg",
  "ban-ki-moon": "/images/africaicons/ban-ki-moon-curriculum.jpg",
  "ban-ki-moon-curriculum": "/images/africaicons/ban-ki-moon-curriculum.jpg",
  "bayo-olukoshi": "/images/africaicons/bayo-olukoshi.jpg",
  "bethlehem-tilahun-alemu": "/images/africaicons/bethlehem-tilahun-alemu.jpg",
  "bethlehem-tilahun-alemu-tech": "/images/africaicons/bethlehem-tilahun-alemu-tech.jpg",
  "bill-drayton": "/images/africaicons/bill-drayton.jpg",
  "bill-gates": "/images/africaicons/bill-gates.jpg",
  "bitange-ndemo": "/images/africaicons/bitange-ndemo.jpg",
  "bright-simons": "/images/africaicons/bright-simons-tech.jpg",
  "bright-simons-tech": "/images/africaicons/bright-simons-tech.jpg",
  "carli-coetzee": "/images/africaicons/carli-coetzee.png",
  "catherine-odora-hoppers": "/images/africaicons/catherine-odora-hoppers.jpg",
  "chika-okeke-agulu": "/images/africaicons/chika-okeke-agulu.jpg",
  "dare-okoudjou": "/images/africaicons/dare-okoudjou.jpg",
  "david-beckham": "/images/africaicons/david-beckham-curriculum.jpg",
  "david-beckham-curriculum": "/images/africaicons/david-beckham-curriculum.jpg",
  "david-sengeh": "/images/africaicons/david-sengeh.jpg",
  "dinaw-mengestu": "/images/africaicons/dinaw-mengestu.jpg",
  "donald-kaberuka": "/images/africaicons/donald-kaberuka-tech.jpg",
  "donald-kaberuka-tech": "/images/africaicons/donald-kaberuka-tech.jpg",
  "eghosa-omoigui": "/images/africaicons/eghosa-omoigui-tech.jpg",
  "eghosa-omoigui-tech": "/images/africaicons/eghosa-omoigui-tech.jpg",
  "elon-musk": "/images/africaicons/elon-musk.jpg",
  "eric-schmidt": "/images/africaicons/eric-schmidt.jpg",
  "erik-hersman": "/images/africaicons/erik-hersman.jpg",
  "fatoumata-ba": "/images/africaicons/fatoumata-ba-tech.jpg",
  "fatoumata-ba-tech": "/images/africaicons/fatoumata-ba-tech.jpg",
  "francis-nyamnjoh": "/images/africaicons/francis-nyamnjoh.jpg",
  "fred-swaniker": "/images/africaicons/fred-swaniker-tech.jpg",
  "fred-swaniker-tech": "/images/africaicons/fred-swaniker-tech.jpg",
  "gordon-brown": "/images/africaicons/gordon-brown-curriculum.jpg",
  "gordon-brown-curriculum": "/images/africaicons/gordon-brown-curriculum.jpg",
  "gordon-brown-tech": "/images/africaicons/gordon-brown-tech.jpg",
  "grace-musila": "/images/africaicons/grace-musila.jpg",
  "hakeem-belo-osagie": "/images/africaicons/hakeem-belo-osagie-tech.jpg",
  "hakeem-belo-osagie-tech": "/images/africaicons/hakeem-belo-osagie-tech.jpg",
  "hakim-adi": "/images/africaicons/hakim-adi.jpg",
  "harry-garuba": "/images/africaicons/harry-garuba.jpg",
  "herman-chinery-hesse": "/images/africaicons/herman-chinery-hesse.jpg",
  "hilda-kragha": "/images/africaicons/hilda-kragha.jpg",
  "hilda-moraa": "/images/africaicons/hilda-moraa-tech.jpg",
  "hilda-moraa-tech": "/images/africaicons/hilda-moraa-tech.jpg",
  "ibrahim-mayaki": "/images/africaicons/ibrahim-mayaki.jpg",
  "idris-elba": "/images/africaicons/idris-elba.jpg",
  "idris-sandu": "/images/africaicons/idris-sandu.jpg",
  "imagesjeffrey-sachs": "/images/africaicons/imagesjeffrey-sachs.jpg",
  "imagessundar-pichai": "/images/africaicons/imagessundar-pichai.jpg",
  "innocent-chukwuma": "/images/africaicons/innocent-chukwuma.jpg",
  "isabel-dos-santos": "/images/africaicons/isabel-dos-santos.jpg",
  "iyinoluwa-aboyeji": "/images/africaicons/iyinoluwa-aboyeji.jpg",
  "iyinoluwa-aboyeji-diaspora": "/images/africaicons/iyinoluwa-aboyeji-diaspora.jpg",
  "jack-ma": "/images/africaicons/jack-ma.jpg",
  "jacqueline-novogratz": "/images/africaicons/jacqueline-novogratz-curriculum.jpg",
  "jacqueline-novogratz-curriculum": "/images/africaicons/jacqueline-novogratz-curriculum.jpg",
  "jacqueline-novogratz-tech": "/images/africaicons/jacqueline-novogratz-tech.jpg",
  "james-mwangi": "/images/africaicons/james-mwangi.jpg",
  "jeff-skoll": "/images/africaicons/jeff-skoll.jpg",
  "jeffrey-sachs": "/images/africaicons/jeffrey-sachs-curriculum.jpg",
  "jeffrey-sachs-curriculum": "/images/africaicons/jeffrey-sachs-curriculum.jpg",
  "jensen-huang": "/images/africaicons/jensen-huang.jpg",
  "john-doerr": "/images/africaicons/john-doerr.jpg",
  "jonathan-jansen": "/images/africaicons/jonathan-jansen.jpg",
  "judith-owigar": "/images/africaicons/judith-owigar-tech.jpg",
  "judith-owigar-tech": "/images/africaicons/judith-owigar-tech.jpg",
  "julia-gillard": "/images/africaicons/julia-gillard-curriculum.jpg",
  "julia-gillard-curriculum": "/images/africaicons/julia-gillard-curriculum.jpg",
  "julia-gillard-tech": "/images/africaicons/julia-gillard-tech.jpg",
  "juliana-rotich": "/images/africaicons/juliana-rotich.jpg",
  "kailash-satyarthi": "/images/africaicons/kailash-satyarthi-curriculum.jpg",
  "kailash-satyarthi-curriculum": "/images/africaicons/kailash-satyarthi-curriculum.jpg",
  "karim-beguir": "/images/africaicons/karim-beguir-tech.jpg",
  "karim-beguir-tech": "/images/africaicons/karim-beguir-tech.jpg",
  "karim-sy": "/images/africaicons/karim-sy.jpg",
  "kennedy-odede": "/images/africaicons/kennedy-odede.jpg",
  "koos-bekker": "/images/africaicons/koos-bekker.jpg",
  "kristalina-georgieva": "/images/africaicons/kristalina-georgieva-curriculum.jpg",
  "kristalina-georgieva-curriculum": "/images/africaicons/kristalina-georgieva-curriculum.jpg",
  "kwame-anthony-appiah": "/images/africaicons/kwame-anthony-appiah.jpg",
  "kwesi-yankah": "/images/africaicons/kwesi-yankah.jpg",
  "laila-lalami": "/images/africaicons/laila-lalami.jpg",
  "lindiwe-dovey": "/images/africaicons/lindiwe-dovey.jpg",
  "maaza-mengiste": "/images/africaicons/maaza-mengiste.jpg",
  "mahmood-mamdani": "/images/africaicons/mahmood-mamdani.png",
  "marc-benioff": "/images/africaicons/marc-benioff.jpg",
  "mark-lowcock": "/images/africaicons/mark-lowcock.jpg",
  "mark-malloch-brown": "/images/africaicons/mark-malloch-brown.jpg",
  "mark-shuttleworth": "/images/africaicons/mark-shuttleworth.jpg",
  "mark-suzman": "/images/africaicons/mark-suzman-curriculum.png",
  "mark-suzman-curriculum": "/images/africaicons/mark-suzman-curriculum.png",
  "mark-zuckerberg": "/images/africaicons/mark-zuckerberg.jpg",
  "martha-nussbaum": "/images/africaicons/martha-nussbaum.jpg",
  "mary-joy-pigozzi": "/images/africaicons/mary-joy-pigozzi.jpg",
  "michelle-obama": "/images/africaicons/michelle-obama-curriculum.jpg",
  "michelle-obama-curriculum": "/images/africaicons/michelle-obama-curriculum.jpg",
  "mike-adenuga": "/images/africaicons/mike-adenuga.jpg",
  "mo-dewji": "/images/africaicons/mo-dewji.jpg",
  "mo-ibrahim": "/images/africaicons/mo-ibrahim.jpg",
  "mohamed-mansour": "/images/africaicons/mohamed-mansour.jpg",
  "mohammed-dewji": "/images/africaicons/mohammed-dewji.jpg",
  "moradewun-adejunmobi": "/images/africaicons/moradewun-adejunmobi.png",
  "naguib-sawiris": "/images/africaicons/naguib-sawiris.jpg",
  "naledi-pandor": "/images/africaicons/naledi-pandor.jpg",
  "ndidi-okonkwo-nwuneli": "/images/africaicons/ndidi-okonkwo-nwuneli.jpg",
  "ngozi-okonjo-iweala": "/images/africaicons/ngozi-okonjo-iweala.jpg",
  "nnedi-okorafor": "/images/africaicons/nnedi-okorafor-philanthropy.jpg",
  "nnedi-okorafor-philanthropy": "/images/africaicons/nnedi-okorafor-philanthropy.jpg",
  "nuruddin-farah": "/images/africaicons/nuruddin-farah.jpg",
  "obiageli-ezekwesili": "/images/africaicons/obiageli-ezekwesili.jpg",
  "okwui-enwezor": "/images/africaicons/okwui-enwezor.jpg",
  "ory-okolloh": "/images/africaicons/ory-okolloh-tech.jpg",
  "ory-okolloh-tech": "/images/africaicons/ory-okolloh-tech.jpg",
  "osei-kwame-despite": "/images/africaicons/osei-kwame-despite.jpg",
  "patrick-awuah": "/images/africaicons/patrick-awuah-tech.jpg",
  "patrick-awuah-tech": "/images/africaicons/patrick-awuah-tech.jpg",
  "patrick-collison": "/images/africaicons/patrick-collison.jpg",
  "paul-tiyambe-zeleza": "/images/africaicons/paul-tiyambe-zeleza.jpg",
  "pierre-omidyar": "/images/africaicons/pierre-omidyar.jpg",
  "pius-adesanmi": "/images/africaicons/pius-adesanmi.jpg",
  "queen-rania": "/images/africaicons/queen-rania.jpg",
  "queen-rania-curriculum": "/images/africaicons/queen-rania-curriculum.jpg",
  "rapelang-rabana": "/images/africaicons/rapelang-rabana.jpg",
  "rebecca-enonchong": "/images/africaicons/rebecca-enonchong.jpg",
  "reed-hastings": "/images/africaicons/reed-hastings-curriculum.jpg",
  "reed-hastings-curriculum": "/images/africaicons/reed-hastings-curriculum.jpg",
  "ruth-meena": "/images/africaicons/ruth-meena.jpg",
  "sabelo-ndlovu-gatsheni": "/images/africaicons/sabelo-ndlovu-gatsheni.jpg",
  "saidiya-hartman": "/images/africaicons/saidiya-hartman.jpg",
  "sal-khan": "/images/africaicons/sal-khan-curriculum.jpg",
  "sal-khan-curriculum": "/images/africaicons/sal-khan-curriculum.jpg",
  "sal-khan-tech": "/images/africaicons/sal-khan-tech.jpg",
  "salim-ismail": "/images/africaicons/salim-ismail.jpg",
  "samuel-esson-jonah": "/images/africaicons/samuel-esson-jonah.jpg",
  "satya-nadella": "/images/africaicons/satya-nadella.jpg",
  "sheikha-moza-bint-nasser": "/images/africaicons/sheikha-moza-bint-nasser-curriculum.jpg",
  "sheikha-moza-bint-nasser-curriculum": "/images/africaicons/sheikha-moza-bint-nasser-curriculum.jpg",
  "sheikha-moza-bint-nasser-tech": "/images/africaicons/sheikha-moza-bint-nasser-tech.jpg",
  "sim-shagaya": "/images/africaicons/sim-shagaya.jpg",
  "sir-fazle-hasan-abed": "/images/africaicons/sir-fazle-hasan-abed.jpg",
  "sir-fazle-hasan-abed-curriculum": "/images/africaicons/sir-fazle-hasan-abed-curriculum.jpg",
  "sir-ken-robinson": "/images/africaicons/sir-ken-robinson.jpg",
  "susan-wojcicki": "/images/africaicons/susan-wojcicki.jpg",
  "tajudeen-abdul-raheem": "/images/africaicons/tajudeen-abdul-raheem.jpg",
  "tayo-oviosu": "/images/africaicons/tayo-oviosu.jpg",
  "thandika-mkandawire": "/images/africaicons/thandika-mkandawire.jpg",
  "tony-elumelu": "/images/africaicons/tony-elumelu-philanthropy.jpg",
  "tony-elumelu-philanthropy": "/images/africaicons/tony-elumelu-philanthropy.jpg",
  "tope-awotona": "/images/africaicons/tope-awotona-tech.jpg",
  "tope-awotona-tech": "/images/africaicons/tope-awotona-tech.jpg",
  "toyin-falola": "/images/africaicons/toyin-falola.jpg",
  "tshilidzi-marwala": "/images/africaicons/tshilidzi-marwala.jpg",
  "tunde-kehinde": "/images/africaicons/tunde-kehinde-tech.jpg",
  "tunde-kehinde-tech": "/images/africaicons/tunde-kehinde-tech.jpg",
  "ulia-gillard": "/images/africaicons/ulia-gillard.jpg",
  "vera-songwe": "/images/africaicons/vera-songwe-tech.jpg",
  "vera-songwe-tech": "/images/africaicons/vera-songwe-tech.jpg",
  "vronique-tadjo": "/images/africaicons/vronique-tadjo.jpg",
  "wale-adeosun": "/images/africaicons/wale-adeosun.jpg",
  "wandia-njoya": "/images/africaicons/wandia-njoya.jpg",
  "william-kamkwamba": "/images/africaicons/william-kamkwamba.jpg",
  "yousriya-loza-sawiris": "/images/africaicons/yousriya-loza-sawiris.webp",
  "yousriya-sawiris": "/images/africaicons/yousriya-sawiris.jpg"
};

// Honorifics that may prefix a nominee slug but never appear in the image filename.
const HONORIFIC_PREFIXES = [
  "dr-",
  "prof-",
  "professor-",
  "sir-",
  "dame-",
  "alhaji-",
  "hon-",
  "rev-",
  "mr-",
  "mrs-",
  "ms-",
  "engr-",
];

// Track / context suffixes we already index, plus narrative qualifiers that
// the migration appended (e.g. "-posthumous", "-global-un-role").
const KNOWN_TRACK_SUFFIXES = [
  "-tech",
  "-curriculum",
  "-philanthropy",
  "-diaspora",
  "-africa",
];

// Known nickname / short-form aliases. Maps an alternate token sequence to
// the canonical slug fragment used in the image manifest.
const NAME_ALIASES: Record<string, string> = {
  "oby-ezekwesili": "obiageli-ezekwesili",
  "chimamanda-adichie": "chimamanda-ngozi-adichie",
  "aliko-dangote": "aliko-dangote", // no image yet; placeholder will render
};

function stripHonorific(slug: string): string {
  for (const p of HONORIFIC_PREFIXES) {
    if (slug.startsWith(p)) return slug.slice(p.length);
  }
  return slug;
}

function lookup(candidate: string): string | undefined {
  if (!candidate) return undefined;
  if (ICON_IMAGE_MANIFEST[candidate]) return ICON_IMAGE_MANIFEST[candidate];
  // Try with each known track suffix swapped in.
  for (const s of KNOWN_TRACK_SUFFIXES) {
    const v = ICON_IMAGE_MANIFEST[candidate + s];
    if (v) return v;
  }
  return undefined;
}

/**
 * Resolve a portrait URL for an Icon nominee.
 *
 * Tolerates:
 *  - exact slug                       ("akinwumi-adesina")
 *  - track-suffixed slug              ("donald-kaberuka-tech")
 *  - honorific prefixes               ("dr-akinwumi-adesina")
 *  - trailing narrative qualifiers    ("amina-mohammed-global-un-role",
 *                                      "chinua-achebe-posthumous-global-impact",
 *                                      "audrey-cheng-africa-based-programmes")
 *  - the unsuffixed nameSlug fallback ("chimamanda-ngozi-adichie")
 */
export const resolveIconImage = (slug: string, nameSlug?: string): string | undefined => {
  const candidates = new Set<string>();
  const push = (s?: string) => {
    if (!s) return;
    candidates.add(s);
    candidates.add(stripHonorific(s));
  };

  push(slug);
  push(nameSlug);

  // Progressively drop trailing dash-segments to peel off narrative qualifiers
  // like "-posthumous", "-global-un-role", "-nigeria-based-influence".
  for (const seed of [slug, nameSlug].filter(Boolean) as string[]) {
    const cleaned = stripHonorific(seed);
    const parts = cleaned.split("-");
    while (parts.length > 1) {
      parts.pop();
      candidates.add(parts.join("-"));
    }
  }

  for (const c of candidates) {
    const hit = lookup(c) ?? (NAME_ALIASES[c] ? lookup(NAME_ALIASES[c]) : undefined);
    if (hit) return hit;
  }
  return undefined;
};
