// Auto-generated nominee data for Christian Education Impact (Africa Regional)
// 4 tabs × 30 nominees = 120 total. All entries launch in "pending_verification" state.

import type { FaithCategoryConfig, FaithNominee } from "./faithCategoryTypes";

const infrastructure: FaithNominee[] = [
  { name: "Catholic Secretariat of Nigeria", desc: "The coordinating body for the Catholic Church in Nigeria, overseeing a large network of Catholic-run schools and education infrastructure across the country.", email: "info@csnigeria.org" },
  { name: "Redeemed Christian Church of God", desc: "A large Pentecostal denomination running schools and education-linked CSR initiatives, including infrastructure support, through its parishes and CSR arm.", email: "csr@rccg.org" },
  { name: "Living Faith Church Worldwide", desc: "A Pentecostal denomination that has established schools and a university, with education infrastructure as part of its broader institutional footprint.", email: "info@lfclife.com" },
  { name: "Methodist Church Nigeria", desc: "A historic mission-founded denomination with a long-standing network of Methodist schools across Nigeria.", email: "info@methodistnigeria.org" },
  { name: "Anglican Church of Nigeria", desc: "A denomination with deep historical roots in establishing mission schools, continuing to run diocesan school networks today.", email: "info@anglican-nig.org" },
  { name: "Seventh-day Adventist Church Nigeria", desc: "A denomination operating a network of Adventist-run schools and education institutions across Nigeria.", email: "education@wnucadventist.org" },
  { name: "Deeper Life Bible Church", desc: "A Pentecostal church that runs an extensive network of schools, including a well-known high school scheme.", email: "info@dclm.org" },
  { name: "Assemblies of God Nigeria", desc: "A Pentecostal denomination supporting education facility development through its local assemblies.", email: "info@aognigeria.org" },
  { name: "The Apostolic Church Nigeria", desc: "A denomination with schools and education infrastructure support as part of its community programming.", email: "info@tacn.org" },
  { name: "Church of Nigeria Baptist Convention", desc: "A historic Baptist denomination with a long-standing network of Baptist-affiliated schools across Nigeria.", email: "info@baptistconvention.org" },
  { name: "Okoa Refuge", desc: "A faith-based relief organisation that includes education facility and learning-space support within its community assistance programming.", email: "info@okoarefuge.org" },
  { name: "Impact Africa", desc: "A Christian development organisation supporting education infrastructure as part of its community impact programming in Africa.", email: "info@impactafrica.org" },
  { name: "Tearfund", desc: "A Christian relief and development organisation whose programming includes education infrastructure support tied to community development.", email: "nigeria@tearfund.org" },
  { name: "Compassion International", desc: "A Christian child-sponsorship organisation whose programming includes school and learning-facility support for sponsored children.", email: "nigeria@compassion.com" },
  { name: "Ethiopia ACT", desc: "A faith-based development organisation in Ethiopia supporting community education infrastructure projects.", email: "info@ethiopiaact.org" },
  { name: "Heart for Africa Ministries", desc: "A Christian ministry supporting education and community infrastructure development across the African communities it serves.", email: "info@heartforafrica.org" },
  { name: "Christian Outreach for Africa", desc: "A Christian outreach organisation supporting school and learning facility development in African communities.", email: "info@christianoutreachafrica.org" },
  { name: "Abundant Favour Christian Ministries", desc: "A Christian ministry whose community programming includes education facility support.", email: "info@abundantfavour.org" },
  { name: "Africa Inland Child & Community Agency", desc: "A faith-based child welfare agency supporting education infrastructure as part of its community development work.", email: "info@aichild.org" },
  { name: "Bright Hope World", desc: "A Christian humanitarian organisation supporting school infrastructure and learning access in the communities it serves.", email: "nigeria@brighthopeworld.com" },
  { name: "Global Ministries", desc: "An ecumenical mission organisation supporting education infrastructure development through its global partnerships.", email: "nigeria@globalministries.org" },
  { name: "World Vision", desc: "A Christian humanitarian organisation whose programming includes education infrastructure development as part of broader community development work.", email: "nigeria@worldvision.org" },
  { name: "Convoy of Hope", desc: "A faith-based relief organisation supporting school facility and learning-space rebuilding as part of its disaster and community response work.", email: "nigeria@convoyofhope.org" },
  { name: "Salvation Army", desc: "A Christian denomination and charity running schools and education facility programmes alongside its social service work.", email: "nigeria@salvationarmy.org" },
  { name: "World Relief", desc: "A Christian relief organisation whose programming includes education infrastructure support as part of community development.", email: "nigeria@worldrelief.org" },
  { name: "Haven Foundation", desc: "A faith-based foundation supporting education facility development in underserved communities.", email: "info@havenfoundation.org" },
  { name: "Tim Tebow Foundation", desc: "A Christian foundation supporting school and learning facility projects as part of its broader charitable programming.", email: "nigeria@tebowfoundation.org" },
  { name: "Fields of Life", desc: "A Christian development organisation supporting school construction and education infrastructure in the communities it serves.", email: "info@fieldsoflife.org" },
  { name: "Bakhita Partnership for Education", desc: "A faith-inspired education partnership supporting school infrastructure and access for vulnerable learners.", email: "info@bakhitapartnership.org" },
  { name: "Lasallian Brothers Education", desc: "A Catholic religious order historically engaged in establishing and running schools across multiple regions.", email: "nigeria@lasallian.org" },
];

const scholarship: FaithNominee[] = [
  { name: "RCCG Scholarship Fund", desc: "A scholarship and bursary scheme run through RCCG's CSR arm supporting students' education costs.", email: "csr@rccg.org" },
  { name: "Living Faith Foundation", desc: "The foundation arm of Living Faith Church running scholarship and education-support programmes.", email: "info@lfclife.com" },
  { name: "Deeper Life High School Scheme", desc: "A scholarship-linked scheme supporting students within the Deeper Life high school network.", email: "scholarships@dclm.org" },
  { name: "Catholic Women Organization Nigeria", desc: "A Catholic women's organisation supporting education scholarships for learners.", email: "info@cwonigeria.org" },
  { name: "Methodist Church Nigeria Board", desc: "A church board administering education scholarships for Methodist-affiliated students.", email: "scholarships@methodistnigeria.org" },
  { name: "Anglican Church Education Board", desc: "An education board running scholarship and youth education funding for Anglican-affiliated students.", email: "youth@anglican-nig.org" },
  { name: "ECWA Education Program", desc: "The education programme of the Evangelical Church Winning All, administering scholarship support for students.", email: "education@ecwa.org.ng" },
  { name: "Salvation Army Nigeria", desc: "The Nigeria territory of the Salvation Army, running education scholarship support alongside its broader social programming.", email: "leadership@nig.salvationarmy.org" },
  { name: "Christian Council of Nigeria", desc: "An ecumenical council coordinating youth scholarship programming across member denominations.", email: "youth@ccnnigeria.org.ng" },
  { name: "Assemblies of God Nigeria", desc: "A Pentecostal denomination supporting scholarship access for students through its youth programming.", email: "youth@agnigeria.org" },
  { name: "Pan African School of Theology", desc: "A theological institution administering scholarships for students pursuing theological education.", email: "info@past.edu" },
  { name: "Langham Partnership International", desc: "A global theological education partnership administering scholarships for students and church leaders.", email: "nigeria@langham.org" },
  { name: "World Council of Churches", desc: "A global ecumenical body that supports education scholarship programmes as part of its broader development work.", email: "info@oikoumene.org" },
  { name: "Brot für die Welt", desc: "A German Protestant development agency supporting scholarship and education access programmes internationally.", email: "nigeria@brot-fuer-die-welt.de" },
  { name: "Black Heart Foundation", desc: "A foundation administering scholarships supporting underserved students' education access.", email: "info@blackheartfoundation.org" },
  { name: "Albert Baker Fund", desc: "A faith-based fund supporting scholarships for students with disabilities pursuing higher education.", email: "info@albertbakerfund.org" },
  { name: "Global Ministries Endowment", desc: "An endowment fund under Global Ministries supporting scholarship access through long-term funding.", email: "nigeria@globalministries.org" },
  { name: "Scholar Leaders", desc: "An international Christian scholarship organisation supporting graduate-level theological and academic education.", email: "info@scholarleaders.org" },
  { name: "West Africa Theological Seminary", desc: "A regional seminary running scholarship support for theological students.", email: "info@wats.edu.ng" },
  { name: "IBSA West Africa", desc: "A regional Baptist association supporting scholarships for students within its network.", email: "info@ibsa.org" },
  { name: "Bangui Evangelical School of Theology", desc: "A theological school in Central Africa administering scholarship support for ministry students.", email: "info@best-bangui.org" },
  { name: "Christian Leadership Scholarship", desc: "A scholarship programme supporting emerging Christian leaders' education access.", email: "info@christianleadershipscholarship.org" },
  { name: "Open Gate Foundation", desc: "A foundation administering scholarships supporting students' education access.", email: "info@opengatefoundation.org" },
  { name: "KCEP Anglican Scholarships", desc: "An Anglican education programme administering scholarship support for students.", email: "info@kcepanglican.org" },
  { name: "LEAD Hubs East Africa", desc: "A regional leadership-development network supporting scholarship access for emerging leaders in East Africa.", email: "info@leadhubseastafrica.org" },
  { name: "INFA-MED Resident Tuition", desc: "A medical education support programme assisting students with tuition costs.", email: "info@infamed.org" },
  { name: "ASEC-SLDI Scholarships", desc: "A leadership-development programme for religious sisters in Africa, supporting their access to higher education.", email: "info@asec-sldi.org" },
  { name: "KENSHA Education Scholarship", desc: "An education scholarship programme supporting students' access to schooling.", email: "info@kensha.org" },
  { name: "East African Christian College", desc: "A regional Christian college administering scholarships for theological and academic students.", email: "info@eacc.ac.ke" },
  { name: "Central Africa Baptist University", desc: "A Baptist university in Central Africa administering scholarship support for its student body.", email: "info@cabu.ac.cd" },
];

const holistic: FaithNominee[] = [
  { name: "Catholic Relief Services Nigeria", desc: "The Nigeria programme of a major Catholic humanitarian agency, combining relief work with education support for vulnerable communities.", email: "nigeria@crs.org" },
  { name: "Christian Aid Nigeria", desc: "A Christian development organisation whose Nigeria work includes holistic education and community development support.", email: "nigeria@christian-aid.org" },
  { name: "Church of Nigeria Anglican Communion", desc: "A denominational body running girls' education and youth welfare programming alongside its broader church activities.", email: "girlsyouth@anglican-nig.org" },
  { name: "ECWA Education Development Unit", desc: "A development unit coordinating holistic education programming within the ECWA denomination.", email: "education@ecwa.org.ng" },
  { name: "Methodist Church Nigeria Services Unit", desc: "A services unit combining education support with broader welfare services for the Methodist community.", email: "socmethodistlagos@yahoo.com" },
  { name: "Redeemed Christian Church of God CSR", desc: "RCCG's corporate social responsibility arm, combining education support with broader community welfare initiatives.", email: "csr@rccg.org" },
  { name: "The Apostolic Church Nigeria", desc: "A denomination combining community welfare work with education-linked support services.", email: "community@tacn-lawna.org" },
  { name: "Christian Teachers Fellowship Nigeria", desc: "A fellowship supporting Christian teachers and education programming in schools.", email: "program.director@teachfornigeria.org" },
  { name: "Scripture Union Nigeria", desc: "A youth-focused Christian organisation combining spiritual outreach with education and youth development support.", email: "outreach@sunigeria.org" },
  { name: "Seventh-day Adventist Church Nigeria", desc: "An SDA programming arm supporting literacy and education access initiatives.", email: "literacy@adventist.org" },
  { name: "Africa New Life Ministries", desc: "A Christian ministry supporting holistic child welfare, including education access, in the communities it serves.", email: "info@africanewlife.org" },
  { name: "UrbanPromise International", desc: "A Christian youth organisation providing wraparound educational and mentorship support for young people.", email: "info@urbanpromiseinternational.org" },
  { name: "World Vision", desc: "A Christian humanitarian organisation supporting holistic child education programming as part of its community development work.", email: "nigeria@worldvision.org" },
  { name: "Okoa Refuge", desc: "A faith-based relief organisation providing holistic education and welfare support to the communities it serves.", email: "info@okoarefuge.org" },
  { name: "Impact Africa", desc: "A Christian development organisation combining education support with broader community impact programming.", email: "info@impactafrica.org" },
  { name: "Tearfund", desc: "A Christian relief and development organisation combining education support with broader community welfare programming.", email: "nigeria@tearfund.org" },
  { name: "Compassion International", desc: "A Christian child-sponsorship organisation providing holistic education, health, and welfare support for sponsored children.", email: "nigeria@compassion.com" },
  { name: "Ethiopia ACT", desc: "A faith-based development organisation in Ethiopia combining education with broader community welfare support.", email: "info@ethiopiaact.org" },
  { name: "Heart for Africa", desc: "A Christian ministry providing holistic education and welfare support across the African communities it serves.", email: "info@heartforafrica.org" },
  { name: "Tim Tebow Foundation", desc: "A Christian foundation supporting holistic education and welfare programmes for children with special needs and underserved communities.", email: "nigeria@tebowfoundation.org" },
  { name: "Christian Outreach for Africa", desc: "A Christian outreach organisation combining education support with broader community welfare initiatives.", email: "info@christianoutreachafrica.org" },
  { name: "Global Ministries", desc: "An ecumenical mission organisation supporting holistic education and community development through its global partnerships.", email: "nigeria@globalministries.org" },
  { name: "West Africa Christian Hospital", desc: "A faith-based hospital combining health services with education support for the communities it serves.", email: "info@wachospital.org" },
  { name: "St. Peter Lutheran Church and School", desc: "A Lutheran church and school combining worship, education, and community welfare services.", email: "info@stpeterlutheran.org" },
  { name: "Life Coaching Ministries", desc: "A Christian ministry supporting holistic personal and educational development through coaching and mentorship.", email: "info@lifecoachingministries.org" },
  { name: "Convoy of Hope", desc: "A faith-based relief organisation combining education support with disaster relief and community development programming.", email: "nigeria@convoyofhope.org" },
  { name: "Salvation Army", desc: "A Christian denomination and charity combining education support with broader social service programming.", email: "nigeria@salvationarmy.org" },
  { name: "World Relief", desc: "A Christian relief organisation combining education support with broader community development programming.", email: "nigeria@worldrelief.org" },
  { name: "Bright Hope World", desc: "A Christian humanitarian organisation combining education access with broader community welfare support.", email: "nigeria@brighthopeworld.com" },
  { name: "Christian Aid Mission", desc: "A Christian mission-support organisation funding holistic education and ministry programmes through partner organisations.", email: "nigeria@christianaidmission.org" },
];

const advocacy: FaithNominee[] = [
  { name: "Christian Association of Nigeria", desc: "The umbrella body for Christian denominations in Nigeria, engaging in advocacy on education policy issues affecting Christian communities.", email: "education@canng.org" },
  { name: "Catholic Secretariat of Nigeria", desc: "The Catholic Church's coordinating body in Nigeria, engaging in education justice and policy advocacy.", email: "justice@csnigeria.org" },
  { name: "RCCG Christian Social Responsibility", desc: "The CSR arm of RCCG, engaging in education advocacy alongside its broader social responsibility programming.", email: "advocacy@rccg.org" },
  { name: "Methodist Church Nigeria Network", desc: "A church network engaging in education advocacy on behalf of its member congregations.", email: "socmethodistlagos@yahoo.com" },
  { name: "Anglican Church Nigeria Group", desc: "An Anglican Church group engaging in education reform advocacy.", email: "advocacy@anglican-nig.org" },
  { name: "ECWA Social & Educational Reform", desc: "A unit within ECWA focused on social and educational reform advocacy.", email: "info@ecwa.org.ng" },
  { name: "Christian Youth Fellowship Nigeria", desc: "A youth fellowship advocating for education rights and access for young people.", email: "rights@cyfglobal.org" },
  { name: "Nigeria Christian Graduate Fellowship", desc: "A graduate fellowship engaging in education advocacy among Christian alumni networks.", email: "ncgfnational2@gmail.com" },
  { name: "Scripture Union West Africa", desc: "A regional Scripture Union body advocating for education standards and access across West Africa.", email: "standards@sunigeria.org" },
  { name: "Lutheran Church of Christ in Nigeria", desc: "A Lutheran denomination engaging with education policy issues affecting its member communities.", email: "president@lccn.org.ng" },
  { name: "Okoa Refuge", desc: "A faith-based relief organisation engaging in advocacy on education access for the communities it serves.", email: "info@okoarefuge.org" },
  { name: "Impact Africa", desc: "A Christian development organisation engaging in advocacy on education access and reform issues.", email: "info@impactafrica.org" },
  { name: "Tearfund", desc: "A Christian relief and development organisation engaging in advocacy on education access alongside its programming.", email: "nigeria@tearfund.org" },
  { name: "Christian Aid", desc: "A Christian development organisation engaging in advocacy on education access and policy reform.", email: "nigeria@christian-aid.org" },
  { name: "Faith and Freedom Coalition", desc: "A faith-based advocacy coalition engaging on education and broader social policy issues.", email: "info@ffcoalition.org" },
  { name: "Acton Institute", desc: "A faith-oriented research and advocacy institute engaging on education policy from a values-based perspective.", email: "info@acton.org" },
  { name: "Atlas Free", desc: "An advocacy organisation engaging on issues including education access for vulnerable populations.", email: "info@atlasfree.org" },
  { name: "ZOE", desc: "A faith-based organisation advocating for orphaned and vulnerable children's education access.", email: "info@zoe.org" },
  { name: "African Council of Religious Leaders", desc: "An interfaith council of religious leaders engaging in advocacy on education and social policy issues across Africa.", email: "info@acrl.org" },
  { name: "All Africa Conference of Churches", desc: "A pan-African ecumenical body advocating for education access and reform across the continent.", email: "info@aacc-ceta.org" },
  { name: "Global Ministries", desc: "An ecumenical mission organisation engaging in advocacy on education access through its global partnerships.", email: "nigeria@globalministries.org" },
  { name: "UNICEF (faith partners)", desc: "UNICEF's faith-engagement programming, partnering with religious communities on education advocacy and awareness.", email: "faith@unicef.org" },
  { name: "UNESCO (faith partners)", desc: "UNESCO's faith-engagement programming, partnering with religious communities on education advocacy and awareness.", email: "faith@unesco.org" },
  { name: "Room to Read", desc: "An international literacy organisation advocating for education access and reading programmes.", email: "nigeria@roomtoread.org" },
  { name: "Global Partnership for Education", desc: "A multilateral education partnership engaging in advocacy for education financing and access globally.", email: "advocacy@globalpartnership.org" },
  { name: "Forum for African Women Educationalists", desc: "A pan-African network advocating for girls' education access and policy reform across the continent.", email: "info@fawe.org" },
  { name: "Christian Aid Mission", desc: "A Christian mission-support organisation engaging in advocacy on education access through its partner network.", email: "nigeria@christianaidmission.org" },
  { name: "SIM International", desc: "An international mission organisation engaging in advocacy on education access alongside its broader mission work.", email: "advocacy@sim.org" },
  { name: "Africa Inland Mission", desc: "A mission organisation engaging in advocacy on education access in the African communities it serves.", email: "director@aimint.org" },
  { name: "Barnabas Fund", desc: "A Christian charity advocating for persecuted communities' access to education and broader support.", email: "advocacy@barnabasfund.org" },
];

export const christianEducationConfig: FaithCategoryConfig = {
  faith: "christian",
  routePath: "/categories/christian-education-impact-africa",
  pageTitle: "Excellence in Christian Education Impact (Africa Regional)",
  pageSubheading: "Recognizing faith-based Christian impact on education across Africa",
  primaryNominateUuid: "5195ec64-2a91-4e59-8fff-8e950ee9fe18",
  subcategories: [
    { title: "Best Educational Infrastructure Development", description: "Christian organisations building, equipping, or rehabilitating schools and learning facilities across Africa.", uuid: "5195ec64-2a91-4e59-8fff-8e950ee9fe18", slug: "christian-schools", tabKey: "infrastructure" },
    { title: "Best Scholarship Program", description: "Christian organisations funding tuition, bursaries, or scholarship pathways for learners.", uuid: "d6c9f60f-7743-43ca-b18c-70a72dca0269", slug: "christian-ngos", tabKey: "scholarship" },
    { title: "Best Holistic Educational Support", description: "Christian organisations combining education with health, nutrition, or wraparound learner support.", uuid: "12e55305-550c-42ad-b444-7c4b1b215d97", slug: "christian-foundations", tabKey: "holistic" },
    { title: "Best Advocacy for Educational Reforms & Awareness Campaigns", description: "Christian organisations campaigning for education policy reform, access, and public awareness.", uuid: null, slug: "christian-advocacy", tabKey: "advocacy" },
  ],
  overviewParagraphs: ["Christian missionary and denominational education has shaped schooling across Africa for centuries — from mission schools that pioneered formal education in many regions to today's diocesan, evangelical, and ecumenical school networks.", "Excellence in Christian Education Impact (Africa Regional) recognises faith-based schools and institutions, scholarship programmes, holistic education support, and advocacy organisations whose sustained programmes advance literacy, values-based education, and access across the continent. Institutional recognition is evaluated under governance and leadership criteria, aligned with SDG 4, SDG 17, and Africa Agenda 2063 Goal 1.", "This recognition is continental in scope: an institution's contribution is assessed by its impact across Africa as a whole, not confined to a single country."],
  whoQualifies: ["Faith-based schools and denominational education boards (Catholic, Protestant, Evangelical, Orthodox, Pentecostal networks)", "Christian education NGOs delivering programmes, scholarships, or teacher training", "Christian scholarship and bursary programmes", "Christian organisations providing holistic education and welfare support", "Advocacy organisations campaigning for education reform and awareness", "Diocesan, mission, or denominational school networks"],
  ediTable: [{"area": "Evidence Quality", "score": 20, "what": "Official records, diocesan/denominational recognition, verified enrolment data"}, {"area": "Education Access", "score": 15, "what": "Learners reached, out-of-school children supported, scholarships"}, {"area": "Learning Quality", "score": 15, "what": "Curriculum quality, values-based education, teacher training"}, {"area": "Equity & Inclusion", "score": 15, "what": "Girls' access, rural learners, low-income students, refugees"}, {"area": "Scale & Reach", "score": 10, "what": "Number of schools, countries, learners, institutions"}, {"area": "Sustainability", "score": 10, "what": "Denominational/diocesan structure, government partnership, institutional continuity"}, {"area": "Innovation", "score": 10, "what": "Curriculum models, digital learning, teacher certification"}, {"area": "Story / Documentary Value", "score": 5, "what": "Human-interest story, visible impact, testimonials"}],
  evidenceNote: "To move a nominee from Pending Verification to Accepted, submit at least 3 of: an official institution page, diocesan/denominational endorsement, enrolment/beneficiary numbers, photos/video of delivery, founding or endowment documentation, a beneficiary testimonial, or independent media coverage. Accepted organisations receive a private link to complete their full public profile, including logo, self-reported description, years active, and beneficiary figures. Only organisational contact details are published before profile completion — individual staff contacts are never made public without separate written consent.",
  recognitionPackage: [
    "Platinum Digital Certificate (GFA Wallet)",
    "Letter of Recognition from SCEF / NESA-Africa",
    "Feature spotlight on NESA TV",
    "Listing in the Christian Education Partners database under SCEF",
    "Private profile edit link to publish logo, description, years active, and beneficiary figures",
  ],
  faqEvidence: "At least 3 of: institution page, diocesan/denominational endorsement, enrolment data, photos/video, founding/endowment documents, testimonial, or media coverage.",
  tabs: {
    infrastructure,
    scholarship,
    holistic,
    advocacy,
  },
};
