/**
 * Diaspora Education Impact 2026 — nominee + champion data.
 * All profiles are pending consent; names/contact details follow the consent
 * publishing gate defined in /consent-guide.
 */

export interface DiasporaNominee {
  role: string;
  org: string; // includes base → home country
  focus: string;
  contact: string;
}

export interface VerifiedChampion {
  name: string;
  org: string;
  focus: string;
  contact: string;
  note?: string;
}

export const NOMINEES_BY_REGION: Record<string, DiasporaNominee[]> = {
  "North Africa": [
    { role: "Cardiologist & Education Philanthropist", org: "Egyptians in UK Trust (UK → Egypt)", focus: "Funded 6 STEM labs; 220 teachers CPD; 4,500 learners.", contact: "Trust website." },
    { role: "Software Engineer", org: "Moroccan Tech in Europe (FR → Morocco)", focus: "Girls' scholarships + WASH in 4 rural schools; 180 beneficiaries.", contact: "Association site." },
    { role: "Robotics Mentor", org: "Tunisian Engineers Germany (DE → Tunisia)", focus: "Robotics kits + mentor network across 25 schools.", contact: "Chapter page." },
    { role: "Education Relief Coordinator", org: "Sudanese Professionals UAE (UAE → Sudan)", focus: "Temporary classrooms, books at 9 sites.", contact: "Federation page." },
    { role: "Energy Specialist", org: "Morocco Solar Diaspora (BE → Morocco)", focus: "Solarized 5 schools; O&M plan with school boards.", contact: "Project microsite." },
    { role: "Assistive Tech Advocate", org: "Egypt STEM Access US (US → Egypt)", focus: "120 devices for visually-impaired learners; teacher training.", contact: "Program page." },
    { role: "Librarian", org: "Libya Heritage Italy (IT → Libya)", focus: "Rehabilitated 3 libraries; digital cataloguing.", contact: "NGO page." },
    { role: "EdTech Founder", org: "Egypt Learning Canada (CA → Egypt)", focus: "Low-data LMS; 4,000 learners; teacher dashboards.", contact: "Company site." },
    { role: "TVET Advisor", org: "Algeria Skills Qatar (QA → Algeria)", focus: "Tooling for lycées techniques; 300 trainees.", contact: "Network site." },
    { role: "Math Coach", org: "Tunisian Math Europe (FR → Tunisia)", focus: "Olympiad prep + teacher coaching; 40 schools.", contact: "Association page." },
    { role: "Network Engineer", org: "Libya Nordic Connect (SE → Libya)", focus: "Routers & internet for 30 schools; uptime tracking.", contact: "Project hub." },
    { role: "Inclusive Designer", org: "Egypt Classrooms US (US → Egypt)", focus: "Re-designed 18 inclusive classrooms; UDL features.", contact: "Org site." },
    { role: "OER Producer", org: "Algeria Science UK (UK → Algeria)", focus: "Arabic science OER; over 1M learners reached.", contact: "OER portal." },
    { role: "Scholarship Lead", org: "Tunisia Scholars CH (CH → Tunisia)", focus: "95 HE scholars; mentoring chain.", contact: "Foundation site." },
    { role: "Chemist", org: "Algeria Labs FR (FR → Algeria)", focus: "Re-equipped 7 chemistry labs; safety training.", contact: "Chapter site." },
    { role: "Psychologist", org: "Sudan MH DE (DE → Sudan)", focus: "Teacher mental-health CPD; 600 staff.", contact: "Program page." },
    { role: "Device Donor", org: "Morocco Digital NL (NL → Morocco)", focus: "1,200 managed tablets (MDM); family literacy.", contact: "Org page." },
    { role: "Career Coach", org: "Egypt Careers IE (IE → Egypt)", focus: "Internship bridges; 300 placements.", contact: "Network site." },
    { role: "Community Builder", org: "Tunisia Hub ES (ES → Tunisia)", focus: "One learning hub; women/youth literacy.", contact: "Hub page." },
    { role: "Relief Coordinator", org: "Sudan School Aid TR (TR → Sudan)", focus: "Feeding + supplies; hardship bursaries.", contact: "Coalition site." },
  ],
  "West Africa": [
    { role: "Tech Investor", org: "Ghana STEM US (US → Ghana)", focus: "10 STEM classrooms; teacher support.", contact: "Foundation site." },
    { role: "Scholarship Lead", org: "Nigeria Scholars UK (UK → Nigeria)", focus: "500 bursaries; retention focus.", contact: "Alumni portal." },
    { role: "Nurse Educator", org: "Sierra Leone Health UK (UK → Sierra Leone)", focus: "Nursing lab; e-learning roll-out.", contact: "Charity page." },
    { role: "ICT Donor", org: "Gambia Learning US (US → Gambia)", focus: "Solar + tablets for rural cluster schools.", contact: "Org site." },
    { role: "Robotics Pioneer", org: "Côte d'Ivoire Makers FR (FR → Côte d'Ivoire)", focus: "Robotics league; 30 schools.", contact: "League page." },
    { role: "Publisher", org: "Guinea Readers CA (CA → Guinea)", focus: "Bilingual readers; 8,000 copies; teacher guides.", contact: "Project page." },
    { role: "Community Dev", org: "Mali Centre FR (FR → Mali)", focus: "Learning centre; night study with solar.", contact: "Centre site." },
    { role: "Systems Engineer", org: "Nigeria Labs CA (CA → Nigeria)", focus: "12 smart labs; MDM analytics; 3 LGAs.", contact: "Company page." },
    { role: "STEM Mentor", org: "Ghana Women in STEM UK (UK → Ghana)", focus: "2,000 girls mentored; alumna pipeline.", contact: "Network site." },
    { role: "Curriculum Lead", org: "Senegal Open Math BE (BE → Senegal)", focus: "Wolof math OER; teacher PD.", contact: "OER portal." },
    { role: "Facilities Donor", org: "Liberia Build US (US → Liberia)", focus: "15 classrooms rehab; furniture & WASH.", contact: "Charity page." },
    { role: "CPD Designer", org: "Nigeria Micro-Cred IE (IE → Nigeria)", focus: "Teacher micro-credentials; 900 teachers.", contact: "Platform page." },
    { role: "Solar Access", org: "Benin Lamps FR (FR → Benin)", focus: "1,500 solar lamps; OER kits.", contact: "Campaign site." },
    { role: "Assistive Tech", org: "Nigeria AT DE (DE → Nigeria)", focus: "200 AT kits; SEN teacher training.", contact: "Org page." },
    { role: "Librarian", org: "Senegal Libraries IT (IT → Senegal)", focus: "Digitized 12 libraries; access cards.", contact: "Library network." },
    { role: "Student Support", org: "Togo Access US (US → Togo)", focus: "Scholarships + transport; 210 learners.", contact: "NGO site." },
    { role: "WASH Lead", org: "Niger Water AE (AE → Niger)", focus: "Boreholes + WASH for desert schools.", contact: "Project page." },
    { role: "Makerspaces", org: "Ghana TVET NL (NL → Ghana)", focus: "6 TVET makerspaces; industry mentors.", contact: "Makerspace hub." },
    { role: "Completion Grants", org: "Sierra Leone Fees US (US → Sierra Leone)", focus: "Cash-for-fees; 300 students.", contact: "Fund page." },
    { role: "Teacher Devices", org: "Gambia LMS UK (UK → Gambia)", focus: "400 laptops; LMS onboarding.", contact: "Program site." },
  ],
  "East Africa": [
    { role: "Lab Builder", org: "Kenya Labs US (US → Kenya)", focus: "County smart labs; 5 counties.", contact: "Foundation site." },
    { role: "Girls' Ed", org: "Uganda STEM UK (UK → Uganda)", focus: "STEM + MHM/WASH; 1,400 girls.", contact: "NGO page." },
    { role: "School Builder", org: "Ethiopia Schools US (US → Ethiopia)", focus: "Built 2 high schools; MoE MoUs.", contact: "Org site." },
    { role: "Scholarship Director", org: "Rwanda Girls BE (BE → Rwanda)", focus: "1,200 scholars; 92% completion.", contact: "Trust page." },
    { role: "TVET Tooling", org: "Tanzania Skills UK (UK → Tanzania)", focus: "10 TVET centres equipped.", contact: "Skills alliance page." },
    { role: "LMS Donor", org: "Somalia e-Learning US (US → Somalia)", focus: "3,000 tablets; LMS + teacher CPD.", contact: "Platform site." },
    { role: "Teacher Trainer", org: "South Sudan Refugee CA (CA → South Sudan)", focus: "200 teachers trained.", contact: "Consortium page." },
    { role: "ICT Hub Lead", org: "Eritrea Tech DE (DE → Eritrea)", focus: "ICT hub + library; uptime 92%.", contact: "Project site." },
    { role: "Digital Literacy", org: "Burundi Youth BE (BE → Burundi)", focus: "500 youth trained.", contact: "NGO site." },
    { role: "Science Labs", org: "Kenya Labs UK (UK → Kenya)", focus: "5 labs; safety SOPs.", contact: "Chapter page." },
    { role: "Robotics Coach", org: "Uganda Robotics US (US → Uganda)", focus: "1,000 learners coached.", contact: "Program page." },
    { role: "School Rehab", org: "Rwanda Schools US (US → Rwanda)", focus: "4 schools rehabilitated.", contact: "Charity site." },
    { role: "Solar Access", org: "Tanzania Solar CA (CA → Tanzania)", focus: "Solarized 12 schools.", contact: "Solar program." },
    { role: "Lecturer Exchange", org: "Ethiopia Fellows IT (IT → Ethiopia)", focus: "50 fellows/year.", contact: "University link." },
    { role: "Women in Tech", org: "Somalia Digital UK (UK → Somalia)", focus: "1,200 women trained.", contact: "Initiative page." },
    { role: "Remote CPD", org: "Kenya Teachers US (US → Kenya)", focus: "3,500 teachers on micro-CPD.", contact: "CPD platform." },
    { role: "Vocational Builder", org: "Uganda TVET US (US → Uganda)", focus: "Built 2 vocational schools.", contact: "Project site." },
    { role: "LMS Roll-out", org: "Ethiopia LMS US (US → Ethiopia)", focus: "LMS in 25 schools.", contact: "EdTech site." },
    { role: "Assistive Tech", org: "Rwanda AT DE (DE → Rwanda)", focus: "Accessibility devices + training.", contact: "Foundation page." },
    { role: "e-Libraries", org: "Kenya Hubs UK (UK → Kenya)", focus: "6 community e-libraries.", contact: "Hub site." },
  ],
  "Central Africa": [
    { role: "School Builder", org: "Cameroon UK (UK → Cameroon)", focus: "4 schools built; PTA co-funding.", contact: "Charity page." },
    { role: "STEM Centres", org: "DRC BE (BE → DRC)", focus: "3 STEM centres; 1,800 learners.", contact: "Association site." },
    { role: "Scholarship Lead", org: "Gabon FR (FR → Gabon)", focus: "500 scholarships; HE readiness.", contact: "Foundation site." },
    { role: "Kit Drive", org: "CAR FR (FR → CAR)", focus: "1,000 school kits; conflict areas.", contact: "NGO page." },
    { role: "Classroom Rehab", org: "Congo-B FR (FR → Republic of Congo)", focus: "6 classrooms; WASH retrofit.", contact: "Program site." },
    { role: "CPD Trainer", org: "Chad FR (FR → Chad)", focus: "200 teachers trained; coaching cycles.", contact: "Network page." },
    { role: "e-Learning", org: "Eq. Guinea ES (ES → Equatorial Guinea)", focus: "National e-learning pilot.", contact: "Platform page." },
    { role: "Coding Coach", org: "Cameroon DE (DE → Cameroon)", focus: "Robotics/coding for 2,000 learners.", contact: "Chapter site." },
    { role: "Library Builder", org: "DRC CA (CA → DRC)", focus: "Two libraries; book drives.", contact: "Charity site." },
    { role: "Regional LMS", org: "CEMAC BE (BE → Regional)", focus: "CEMAC e-learning pilot.", contact: "Alliance page." },
    { role: "Book Donor", org: "Gabon FR (FR → Gabon)", focus: "3,000 books; teacher guides.", contact: "Project site." },
    { role: "Solar Classrooms", org: "Cameroon CA (CA → Cameroon)", focus: "Solar classrooms; uptime SLA.", contact: "NGO page." },
    { role: "Med Skills Lab", org: "DRC BE (BE → DRC)", focus: "Medical faculty skills lab.", contact: "University page." },
    { role: "ICT Kits", org: "Congo-B FR (FR → Congo-B)", focus: "ICT kits; 20 schools.", contact: "Association page." },
    { role: "School Builder", org: "Chad DE (DE → Chad)", focus: "Two schools; 1,100 learners.", contact: "Fund site." },
    { role: "Scholarship Hub", org: "Equatorial Africa ES (ES → Regional)", focus: "800 scholarships.", contact: "Hub page." },
    { role: "Mentorship Lead", org: "Cameroon US (US → Cameroon)", focus: "Teacher mentorship; 400 teachers.", contact: "Network site." },
    { role: "Summit Convenor", org: "Central Africa BE (BE → Regional)", focus: "Diaspora education summit.", contact: "Event page." },
    { role: "STEM Labs", org: "DRC US (US → DRC)", focus: "10 STEM labs; 6 provinces.", contact: "Project site." },
    { role: "Ed-Health Integrator", org: "Regional FR (FR → Regional)", focus: "School health + learning.", contact: "Coalition site." },
  ],
  "Southern Africa": [
    { role: "Rural Builder", org: "South Africa UK (UK → South Africa)", focus: "Rural schools program; 2,000 learners.", contact: "Charity site." },
    { role: "STEM Labs", org: "Zimbabwe UK (UK → Zimbabwe)", focus: "10 labs; inspection toolkits.", contact: "Network page." },
    { role: "Girls' Scholarships", org: "Malawi CA (CA → Malawi)", focus: "2,000 scholarships; retention +18 pts.", contact: "Fund page." },
    { role: "School Rehab", org: "Zambia US (US → Zambia)", focus: "15 school rehabs; PTA match.", contact: "Org site." },
    { role: "Open Library", org: "Namibia DE (DE → Namibia)", focus: "OA digital library; 50 schools.", contact: "Library site." },
    { role: "Teacher Exchange", org: "Botswana UK (UK → Botswana)", focus: "80 teacher exchanges.", contact: "Embassy partner page." },
    { role: "ICT Labs", org: "Lesotho US (US → Lesotho)", focus: "ICT labs; LMS onboarding.", contact: "Program site." },
    { role: "School Rehab", org: "Mozambique PT (PT → Mozambique)", focus: "6 rehabs; cyclone-safe standards.", contact: "NGO site." },
    { role: "HE Devices", org: "Angola PT (PT → Angola)", focus: "100 PCs to HEIs; labs wiring.", contact: "University link." },
    { role: "Mentorship", org: "South Africa UK (UK → South Africa)", focus: "5,000 mentees; STEM careers.", contact: "Network page." },
    { role: "TVET Equipment", org: "Zimbabwe US (US → Zimbabwe)", focus: "3 TVET centres equipped.", contact: "Project page." },
    { role: "Teacher Bursaries", org: "Zambia UK (UK → Zambia)", focus: "120 bursaries.", contact: "Fund page." },
    { role: "Solar Schools", org: "Malawi DE (DE → Malawi)", focus: "Solarized 5 schools; SLA.", contact: "Solar program." },
    { role: "Robotics", org: "Botswana US (US → Botswana)", focus: "1,000 learners in robotics.", contact: "Chapter site." },
    { role: "Career Hubs", org: "Namibia CA (CA → Namibia)", focus: "Guidance hubs; tracer studies.", contact: "NGO site." },
    { role: "Literacy Kits", org: "Angola FR (FR → Angola)", focus: "Literacy kits; 40 schools.", contact: "Charity page." },
    { role: "Coding Bootcamp", org: "Mozambique PT (PT → Mozambique)", focus: "1 bootcamp; 300 graduates.", contact: "Bootcamp page." },
    { role: "Girls' STEM", org: "Eswatini US (US → Eswatini)", focus: "STEM grants; 600 girls.", contact: "Org page." },
    { role: "Literacy+STEM", org: "South Africa US (US → South Africa)", focus: "10,000 youth.", contact: "Coalition site." },
    { role: "SADC Teacher Training", org: "Regional Multi-base (→ SADC)", focus: "Regional grant for teacher CPD.", contact: "SADC hub." },
  ],
};

export const VERIFIED_CHAMPIONS: VerifiedChampion[] = [
  {
    name: "Patrick G. Awuah Jr.",
    org: "Founder & President, Ashesi University Foundation (USA/Ghana → Ghana)",
    focus: "University-level STEM and ethics education; scholarships, labs, and faculty development.",
    contact: "Ashesi University Foundation — advancement/communications team (public contact page).",
  },
  {
    name: "Kenya Diaspora Alliance — Education/Skills Chair",
    org: "Multi-base → Kenya",
    focus: "Smart labs, skills and careers linkage; Secretariat provides official phone contacts.",
    contact: "KDA Secretariat (public).",
    note: "Individual name to be confirmed after consent.",
  },
  {
    name: "Zimbabwe Diaspora Network — UK Education Lead",
    org: "UK → Zimbabwe",
    focus: "STEM lab equipment and school support via diaspora network.",
    contact: "ZDN-BI website (public contact page).",
    note: "Individual name to be confirmed after consent.",
  },
  {
    name: "Building Schools for Africa — UK Champion",
    org: "UK → Cameroon",
    focus: "School construction and rehabilitation in partnership with SHUMAS; long-running diaspora-led effort.",
    contact: "Building Schools for Africa website (public).",
    note: "Individual name to be confirmed after consent.",
  },
  {
    name: "Renaissance of Moroccans of the World — Education Lead",
    org: "France → Morocco",
    focus: "Community education, training, and youth programs run by a diaspora association.",
    contact: "Official email/phone (public site).",
    note: "Individual name to be confirmed after consent.",
  },
];

export const CHAMPIONS_BY_REGION: Record<string, DiasporaNominee[]> = {
  "West Africa": [
    { role: "Education Program Lead", org: "NIDO Europe — Education Desk (UK/EU → Nigeria)", focus: "ICT labs, textbook drives, teacher CPD with state SUBEBs (2021–2025).", contact: "NIDO Europe — Contact/Chapters page." },
    { role: "STEM Fund Chair", org: "Ghana Diaspora Education Network (UK → Ghana)", focus: "STEM classrooms, robotics clubs, girls' bursaries across Ashanti/Volta.", contact: "Network contact page." },
    { role: "Libraries & Labs Patron", org: "Sierra Leone UK Alumni Network (UK → Sierra Leone)", focus: "Rehabilitated district libraries; re-equipped university STEM block.", contact: "Alumni/association site." },
    { role: "Devices & Solar Schools Coordinator", org: "Gambia Diaspora Education Trust (USA → Gambia)", focus: "Solarizing rural schools; tablets/MDM rollout for classroom use.", contact: "Trust website." },
    { role: "Scholarship & Bilingual Content Lead", org: "Guinean Diaspora Readers (Canada → Guinea)", focus: "French-local bilingual readers with teacher guides; literacy camps.", contact: "Project page." },
    { role: "Community Learning Centre Founder", org: "Mali Diaspora Literacy Network (France → Mali)", focus: "After-school literacy; solar night-study hub serving low-income youth.", contact: "Network site." },
    { role: "Smart Labs Program Lead", org: "Nigeria-Canada Alumni Forum (Canada → Nigeria)", focus: "Smart lab kits, teacher onboarding, MDM analytics in public schools.", contact: "Forum website." },
    { role: "Girls in STEM Mentor-in-Chief", org: "Ghana Women in STEM UK (UK → Ghana)", focus: "Mentorship cohorts, STEM camps, role-model talks; 2,000+ girls; alumna pipeline.", contact: "Network contact page." },
    { role: "Open Math Curriculum Coordinator", org: "Senegal Wolof OER Collective (Belgium → Senegal)", focus: "Local-language math OER with teacher PD communities of practice; 50+ schools.", contact: "OER portal." },
    { role: "School Rehab & Furniture Sponsor", org: "Liberia Alumni US (USA → Liberia)", focus: "Classroom rehab, desks, and basic WASH in rural/urban districts.", contact: "Alumni/charity page." },
    { role: "Teacher Micro-Credential Architect", org: "Nigeria Micro-CPD Network (Ireland → Nigeria)", focus: "Online micro-CPD, observation rubrics, QA integration with schools; 900+ teachers.", contact: "Platform page." },
    { role: "Solar Study Lamp & OER Coordinator", org: "Benin Diaspora Education (France → Benin)", focus: "Solar study kits and open readers for junior secondary pupils; 1,500 lamps; 30 schools.", contact: "Campaign site." },
    { role: "Assistive Tech Lead", org: "Nigeria AT for Learning (Germany → Nigeria)", focus: "AT kits for SEN learners; inclusive-education teacher training; 200+ kits.", contact: "Org contact page." },
    { role: "Library Digitization Champion", org: "Senegal Library Network Diaspora (Italy → Senegal)", focus: "Library cataloguing, access cards, youth literacy programs; 12 libraries digitized.", contact: "Library network site." },
    { role: "Scholarship & Transport Stipends Patron", org: "Togo Access US (USA → Togo)", focus: "Completion grants and transport stipends for at-risk students; 210 learners.", contact: "NGO site." },
    { role: "Desert-School WASH Lead", org: "Niger Water & Schools (UAE → Niger)", focus: "Boreholes and WASH retrofits to raise attendance and retention; multi-LGA.", contact: "Project page." },
    { role: "TVET Makerspaces Founder", org: "Ghana TVET NL (Netherlands → Ghana)", focus: "Makerspaces with industry mentors and placement pathways; 6 sites.", contact: "Makerspace hub site." },
    { role: "Fees Completion Grants Sponsor", org: "Sierra Leone Fees US (USA → Sierra Leone)", focus: "Cash-for-fees to prevent dropout in senior secondary; 300 students retained.", contact: "Fund page." },
    { role: "Teacher Laptops & LMS Coordinator", org: "Gambia LMS UK (UK → Gambia)", focus: "Teacher laptops; LMS onboarding and usage support; 400 devices; 30+ schools.", contact: "Program site." },
    { role: "Scholarships & Digital Skills Lead", org: "Cape Verde Global Education PT (Portugal → Cabo Verde)", focus: "Scholarships, bilingual content, digital-skills bootcamps across islands; 3,000+ learners.", contact: "Foundation site." },
  ],
  "East Africa": [
    { role: "County Smart Labs Lead", org: "Kenya Diaspora Alliance — Education Desk (US → Kenya)", focus: "County-level smart labs; teacher onboarding; MDM analytics.", contact: "KDA Secretariat page." },
    { role: "Girls' STEM & MHM Advocate", org: "Uganda STEM UK (UK → Uganda)", focus: "Girls' STEM clubs; MHM/WASH; mentors; 1,400 girls.", contact: "Network site." },
    { role: "School Builder", org: "Ethiopia Schools US (US → Ethiopia)", focus: "Two secondary schools; MoE MoUs; STEM labs.", contact: "Org site." },
    { role: "Scholarship Director", org: "Rwanda Girls Scholarship Trust EU Chapter (BE → Rwanda)", focus: "1,200 scholars; completion above 90%.", contact: "Trust contact page." },
    { role: "TVET Tooling Coordinator", org: "Tanzania Skills Alliance UK (UK → Tanzania)", focus: "TVET equipment for 10 centres; safety SOPs.", contact: "Alliance site." },
    { role: "LMS/Devices Lead", org: "Somalia e-Learning US (US → Somalia)", focus: "3,000 tablets; LMS; teacher CPD.", contact: "Platform site." },
    { role: "Teacher Trainer — Refugee Schools", org: "South Sudan Educators Canada (CA → South Sudan)", focus: "200 teachers trained; coaching cycles.", contact: "Consortium page." },
    { role: "ICT Hub Lead", org: "Eritrea Tech DE (DE → Eritrea)", focus: "ICT hub + community library; uptime tracking.", contact: "Project site." },
    { role: "Digital Literacy Coach", org: "Burundi Youth Digital EU (BE → Burundi)", focus: "500 youth; entry-level coding.", contact: "NGO site." },
    { role: "Science Labs Coordinator", org: "Kenya Labs UK (UK → Kenya)", focus: "5 labs; lab safety & usage logs.", contact: "Chapter page." },
    { role: "Robotics Coach", org: "Uganda Robotics US (US → Uganda)", focus: "1,000 learners; competitions & mentors.", contact: "Program page." },
    { role: "School Rehab Lead", org: "Rwanda Schools US (US → Rwanda)", focus: "4 schools rehabilitated; WASH retrofits.", contact: "Charity site." },
    { role: "Solar Schools Coordinator", org: "Tanzania Solar CA (CA → Tanzania)", focus: "12 schools solarized; O&M budget lines.", contact: "Program site." },
    { role: "Lecturer Exchange Convenor", org: "Ethiopia Fellows EU (IT → Ethiopia)", focus: "50 fellows/year; HE capacity building.", contact: "University link." },
    { role: "Women in Tech Lead", org: "Somalia Digital UK (UK → Somalia)", focus: "1,200 women trained; job-link sessions.", contact: "Initiative page." },
    { role: "Remote CPD Architect", org: "Kenya Teachers US (US → Kenya)", focus: "3,500 teachers; micro-credentials.", contact: "CPD platform." },
    { role: "Vocational School Builder", org: "Uganda TVET US (US → Uganda)", focus: "Two TVET schools; placement pathways.", contact: "Project site." },
    { role: "LMS Roll-out Lead", org: "Ethiopia LMS US (US → Ethiopia)", focus: "LMS in 25 schools; teacher dashboards.", contact: "EdTech site." },
    { role: "Assistive Tech Coordinator", org: "Rwanda AT DE (DE → Rwanda)", focus: "AT devices; inclusion training.", contact: "Foundation page." },
    { role: "e-Libraries Founder", org: "Kenya Hubs UK (UK → Kenya)", focus: "6 community e-libraries; open resources.", contact: "Hub site." },
  ],
  "Central Africa": [
    { role: "School Builder", org: "Cameroon UK Education Trust (UK → Cameroon)", focus: "4 schools built; PTA co-funding.", contact: "Charity page." },
    { role: "STEM Centres Coordinator", org: "DRC Scholars Belgium (BE → DRC)", focus: "3 STEM centres; 1,800 learners.", contact: "Association site." },
    { role: "Scholarship Director", org: "Gabon Education Foundation EU (FR → Gabon)", focus: "500 HE scholarships; mentoring.", contact: "Foundation site." },
    { role: "School Kits Lead", org: "CAR Diaspora for Education (FR → CAR)", focus: "1,000 kits; crisis districts.", contact: "NGO page." },
    { role: "Classroom Rehab Coordinator", org: "Congo-Brazzaville Educators EU (FR → Rep. of Congo)", focus: "6 classrooms rehab; WASH retrofit.", contact: "Program site." },
    { role: "Teacher CPD Trainer", org: "Chad Educators France (FR → Chad)", focus: "200 teachers; coaching cycles.", contact: "Network page." },
    { role: "National e-Learning Pilot Lead", org: "Equatorial Guinea EdTech ES (ES → Eq. Guinea)", focus: "Platform + teacher onboarding.", contact: "Platform site." },
    { role: "Coding & Robotics Coach", org: "Cameroon DE STEM (DE → Cameroon)", focus: "2,000 learners; competitions.", contact: "Chapter site." },
    { role: "Library Builder", org: "DRC Canada Book Trust (CA → DRC)", focus: "Two libraries; book drives.", contact: "Charity site." },
    { role: "Regional LMS Convenor", org: "CEMAC e-Learning Alliance (BE → Regional)", focus: "Regional pilot; shared OER.", contact: "Alliance page." },
    { role: "Book Donation Lead", org: "Gabon Diaspora Literacy EU (FR → Gabon)", focus: "3,000 books; teacher guides.", contact: "Project site." },
    { role: "Solar Classrooms Lead", org: "Cameroon Canada Education Group (CA → Cameroon)", focus: "Solar classrooms; uptime SLA.", contact: "NGO page." },
    { role: "Med Skills Lab Coordinator", org: "DRC Academic Solidarity EU (BE → DRC)", focus: "Medical faculty skills lab; teaching aids.", contact: "University page." },
    { role: "ICT Kits Lead", org: "Congo-B Educators France (FR → Rep. of Congo)", focus: "ICT kits in 20 schools.", contact: "Association page." },
    { role: "School Builder", org: "Chad Diaspora Germany (DE → Chad)", focus: "Two schools; inclusive features.", contact: "Fund site." },
    { role: "Scholarship Hub Coordinator", org: "Equatorial Africa Scholars (ES → Regional)", focus: "800 scholarships; equity focus.", contact: "Hub page." },
    { role: "Teacher Mentorship Lead", org: "Cameroon US Educators (US → Cameroon)", focus: "400 teachers; mentorship cascade.", contact: "Network site." },
    { role: "Diaspora Summit Convenor", org: "Central Africa Education Forum (BE → Regional)", focus: "Annual diaspora conference; policy links.", contact: "Event page." },
    { role: "STEM Labs Coordinator", org: "DRC US STEM (US → DRC)", focus: "10 STEM labs; 6 provinces.", contact: "Project site." },
    { role: "Ed-Health Integrator", org: "Regional School Health Coalition (FR → Regional)", focus: "School health + learning outcomes.", contact: "Coalition site." },
  ],
  "Southern Africa": [
    { role: "Rural Schools Builder", org: "South Africa UK Education Forum (UK → South Africa)", focus: "Rural school builds; 2,000 learners.", contact: "Charity page." },
    { role: "STEM Labs Coordinator", org: "Zimbabwe Diaspora Education Trust UK (UK → Zimbabwe)", focus: "10 labs; inspection toolkits.", contact: "Network site." },
    { role: "Girls' Scholarship Lead", org: "Malawi Canada Education Foundation (CA → Malawi)", focus: "2,000 scholarships; retention gains.", contact: "Foundation site." },
    { role: "School Rehab Lead", org: "Zambia Global Academic Network (US → Zambia)", focus: "15 school rehabs; PTA co-funding.", contact: "Org site." },
    { role: "Open Access Library Founder", org: "Namibia Scholars Germany (DE → Namibia)", focus: "OA digital library; 50 schools.", contact: "Library site." },
    { role: "Teacher Exchange Convenor", org: "Botswana Education Abroad Alliance (UK → Botswana)", focus: "80 exchanges; peer-learning cycles.", contact: "Embassy partner page." },
    { role: "ICT Labs Lead", org: "Lesotho Edu US (US → Lesotho)", focus: "ICT labs; LMS onboarding.", contact: "Program site." },
    { role: "School Rehab Coordinator", org: "Mozambique Diaspora PT (PT → Mozambique)", focus: "6 cyclone-safe rehabs.", contact: "NGO site." },
    { role: "HE Devices Donor", org: "Angola Academic Network EU (PT → Angola)", focus: "100 PCs to universities; wiring & maintenance.", contact: "University link." },
    { role: "Mentorship Director", org: "South Africa Diaspora Women in Education (UK → South Africa)", focus: "5,000 mentees; career guidance.", contact: "Network page." },
    { role: "TVET Equipment Lead", org: "Zimbabwe Engineers Abroad (US → Zimbabwe)", focus: "TVET equipment for 3 centres.", contact: "Project page." },
    { role: "Teacher Bursaries Coordinator", org: "Zambia-UK Alumni Forum (UK → Zambia)", focus: "120 teacher bursaries.", contact: "Fund page." },
    { role: "Solar Schools Lead", org: "Malawi-Germany Scholars League (DE → Malawi)", focus: "Solar for 5 schools; uptime logs.", contact: "Solar program." },
    { role: "Robotics Coordinator", org: "Botswana STEM Abroad (US → Botswana)", focus: "1,000 learners; robotics training.", contact: "Chapter site." },
    { role: "Career Hubs Founder", org: "Namibia-Canada Education Hub (CA → Namibia)", focus: "Career hubs; tracer studies.", contact: "NGO site." },
    { role: "Literacy Kits Lead", org: "Angola Diaspora Educators FR (FR → Angola)", focus: "Literacy kits; 40 schools.", contact: "Charity page." },
    { role: "Coding Bootcamp Founder", org: "Mozambique Diaspora Tech Forum (PT → Mozambique)", focus: "Coding bootcamp; 300 grads.", contact: "Bootcamp page." },
    { role: "Girls' STEM Grants Lead", org: "Eswatini Diaspora Education Fund (US → Eswatini)", focus: "Girls' STEM grants; 600 beneficiaries.", contact: "Org page." },
    { role: "Literacy+STEM Convenor", org: "South Africa Diaspora Education Circle (US → South Africa)", focus: "10,000 youth; blended programs.", contact: "Coalition site." },
    { role: "SADC Teacher Training Lead", org: "SADC Diaspora Education Collective (Multi-base → SADC)", focus: "Regional CPD grant; cross-border cohorts.", contact: "SADC hub." },
  ],
  "North Africa": [
    { role: "STEM Labs Patron", org: "Egypt-UK Academic Partnership Forum (UK → Egypt)", focus: "Funding 3 STEM schools; teacher CPD.", contact: "Forum/HE partner page." },
    { role: "ICT in Schools Lead", org: "Morocco Global Education Trust FR Chapter (FR → Morocco)", focus: "ICT in 20 schools; local-language content.", contact: "Trust site." },
    { role: "HE Scholarships Director", org: "Tunisia Diaspora Academic Society (FR → Tunisia)", focus: "500 scholarships; mentoring.", contact: "Society contact page." },
    { role: "Solar & e-Learning Coordinator", org: "Algeria-France Education Alliance (FR → Algeria)", focus: "Solar labs; e-learning hubs.", contact: "Alliance site." },
    { role: "School Rebuild Lead", org: "Libya Education & Peace Foundation EU (IT → Libya)", focus: "Rebuild schools; USD 150k+ equivalent.", contact: "Foundation site." },
    { role: "EiE Coordinator", org: "Sudan Diaspora Education Network UK (UK → Sudan)", focus: "Temporary schools; learners in crisis.", contact: "Network page." },
    { role: "Science Equipment Donor", org: "Egypt Diaspora Scientists Group (US → Egypt)", focus: "Research equipment; student labs.", contact: "Group site." },
    { role: "Literacy & Women's Ed Lead", org: "Morocco-Belgium Education League (BE → Morocco)", focus: "Literacy for 2,000 women; community tutors.", contact: "League site." },
    { role: "Teacher Training Coordinator", org: "Tunisia-Germany Scholars Forum (DE → Tunisia)", focus: "200 staff trained; observation cycles.", contact: "Forum page." },
    { role: "EdTech Grants Lead", org: "Algeria-Canada Education Group (CA → Algeria)", focus: "EdTech grants; device labs.", contact: "Group site." },
    { role: "STEM Materials Coordinator", org: "Sudanese Educators Abroad GCC (UAE/Qatar → Sudan)", focus: "STEM kits; teacher workshops.", contact: "Chapter page." },
    { role: "Library Rehab Lead", org: "Libyan Global Education Initiative UK (UK → Libya)", focus: "3 libraries rebuilt; cataloguing.", contact: "Initiative site." },
    { role: "Coding Schools Convenor", org: "Morocco STEM Diaspora Network US (US → Morocco)", focus: "Coding schools in 3 cities.", contact: "Network site." },
    { role: "Exchange & Training Lead", org: "Egypt-Italy Academic League (IT → Egypt)", focus: "Student exchanges; faculty training.", contact: "League site." },
    { role: "Online Learning Lead", org: "Algeria-UK University Network (UK → Algeria)", focus: "Online learning platform roll-out.", contact: "Network page." },
    { role: "Women in Education Coordinator", org: "Tunisia-France Women in Education (FR → Tunisia)", focus: "Mentorship & parity initiatives.", contact: "Chapter site." },
    { role: "Digital Teacher Training Lead", org: "Libya-USA Education Forum (US → Libya)", focus: "Teacher digital training cohorts.", contact: "Forum site." },
    { role: "National Literacy Coordinator", org: "Sudan Diaspora Literacy Alliance (QA → Sudan)", focus: "10,000 books; adult literacy.", contact: "Alliance page." },
    { role: "HE Research Supporter", org: "Egypt-France Research Collaboration Hub (FR → Egypt)", focus: "Higher-ed equipment; lab support.", contact: "Hub page." },
    { role: "Regional Literacy Convenor", org: "North Africa Diaspora Education Collective (Multi-base → Regional)", focus: "Cross-border literacy program; multi-country reach.", contact: "Collective site." },
  ],
};

export const SUBCATEGORIES = [
  { track: "01", title: "Diaspora Association Educational Partnership Award", slug: "9d4d70e8-0d49-432b-8275-55a5725f7d45", desc: "Recognises registered diaspora associations or national unions (e.g. NIDO chapters, alumni groups) that have channelled collective resources into scholarships, school infrastructure, teacher training, or digital learning access across African regions (≥ USD 50,000 verified, 2021–2025)." },
  { track: "02", title: "Outstanding Individual Diaspora Education Champion", slug: "e59bd164-6c73-4a51-9f23-15e0bcaa1114", desc: "Honours individual Africans abroad who have consistently provided financial, professional, or technical support — from sponsoring classrooms to donating devices, mentoring teachers, or leading global advocacy for equitable education." },
  { track: "03", title: "Diaspora-Led Institutional Development & Capacity-Building Award", slug: "160989b3-8028-4ea6-88ef-0137f9e5f225", desc: "For professional networks or experts in academia, health, ICT, or engineering whose knowledge transfer, policy support, or technical consulting directly strengthened African educational institutions, universities, or ministries." },
  { track: "04", title: "Diaspora Philanthropy & CSR Impact Recognition", slug: "e039aefe-14aa-4ef1-8ca8-f8f62b52f28a", desc: "Celebrates private diaspora-owned businesses or CSR foundations funding education initiatives — feeding programs, libraries, e-learning, or TVET skills labs — in partnership with local governments or NGOs." },
  { track: "05", title: "Diaspora Scholarship Programmes", slug: "42bc39f2-7f52-4561-92f9-f0e62c457d23", desc: "Structured scholarship funds or bursary schemes run by diaspora groups covering fees, devices, transport, or living stipends for African students." },
  { track: "06", title: "Diaspora Digital Education Innovation Award", slug: "c6ca46d0-87db-4fbe-8720-8b4ea99ca023", desc: "Highlights innovators developing platforms or apps for remote learning, teacher support, or data management serving schools across African regions." },
];

export const PRIMARY_NOMINATE_HREF = "/nominate?subcategory=9d4d70e8-0d49-432b-8275-55a5725f7d45";
