// Auto-generated nominee data for Islamic Education Impact (Africa Regional)
// 4 tabs × 30 nominees = 120 total. All entries launch in "pending_verification" state.

import type { FaithCategoryConfig, FaithNominee } from "./faithCategoryTypes";

const infrastructure: FaithNominee[] = [
  { name: "Nasrul-Lahi-L-Fatih Society (NASFAT)", desc: "A Lagos-founded Islamic society that runs community mosques, schools, and learning centres, with infrastructure projects supporting Islamiyya and integrated education across its chapters.", email: "info@nasfat.org" },
  { name: "Ansar-Ud-Deen Society of Nigeria", desc: "One of Nigeria's oldest Islamic societies, historically active in establishing and running schools and learning facilities across Southwestern Nigeria.", email: "info@auds.org.ng" },
  { name: "Federation of Muslim Women's Associations in Nigeria", desc: "A national umbrella body for Muslim women's associations that supports school facilities and girls' education access through its member chapters.", email: "info@fomwan.org" },
  { name: "Muslim Students Society of Nigeria", desc: "A student-led Islamic organisation active on Nigerian campuses, supporting facility improvements and learning spaces through chapter-level outreach.", email: "info@mssnigeria.org" },
  { name: "The Muslim Congress", desc: "A Lagos-based Islamic organisation engaged in education development activities, including facility and learning-space support for affiliated institutions.", email: "info@tmc.org.ng" },
  { name: "Al-Habibiyyah Islamic Society", desc: "An Islamic society supporting school infrastructure and community learning facilities in the areas it operates.", email: "info@alhabibiyyah.org" },
  { name: "Islamic Education Trust Minna", desc: "An education-focused trust historically involved in establishing and supporting schools that combine Islamic and secular curricula.", email: "info@ietminna.org" },
  { name: "Muslim Ummah of South-West Nigeria", desc: "A regional Muslim umbrella organisation supporting education facility projects across South-West Nigeria.", email: "info@muswen.org.ng" },
  { name: "Al-Furqan Foundation", desc: "A foundation supporting Quranic school infrastructure and learning facility development.", email: "info@furqaan.org" },
  { name: "Jaiz Charity & Development Foundation", desc: "The charitable foundation arm of a Nigerian non-interest financial institution, funding education infrastructure projects as part of its development mandate.", email: "info@jaizfoundation.org.ng" },
  { name: "Al-Kisa Foundation", desc: "A foundation supporting education facility development in underserved communities.", email: "info@alkisa.org" },
  { name: "Islamic Relief Worldwide", desc: "An international Islamic humanitarian organisation that includes school infrastructure rebuilding and rehabilitation as part of its relief and development programming.", email: "nigeria@islamic-relief.org" },
  { name: "Awqaf Africa", desc: "A pan-African Islamic endowment (Waqf) network that channels endowment funding toward education infrastructure projects.", email: "info@awqafafrica.org" },
  { name: "Aga Khan Development Network", desc: "A network of development agencies that invests in education infrastructure and quality improvement as part of its broader development mandate across Africa and Asia.", email: "nigeria@akdn.org" },
  { name: "Islamic Education Trust Ghana", desc: "An education trust supporting school building and infrastructure improvement for Islamic education institutions in Ghana.", email: "info@ietghana.org" },
  { name: "Al-Islah Charity", desc: "A charity supporting education facility and infrastructure development in the communities it serves.", email: "info@alislahcharity.org" },
  { name: "Lives and Livelihoods Fund", desc: "A multilateral Islamic development fund supporting education and health infrastructure in member countries.", email: "info@llfund.org" },
  { name: "Islamic Solidarity Fund Niger", desc: "A solidarity fund supporting education infrastructure projects in Niger and the wider Sahel region.", email: "info@isfniger.org" },
  { name: "ICODEHS", desc: "An Islamic development organisation supporting education and health infrastructure projects.", email: "info@icodehs.org" },
  { name: "Qatar Fund for Development", desc: "A development fund supporting education infrastructure financing across multiple African countries.", email: "nigeria@qfd.org" },
  { name: "Islamic Development Bank", desc: "A multilateral development bank financing education infrastructure projects across its member states, including in Africa.", email: "nigeria@isdb.org" },
  { name: "Bilal Muslim Mission Kenya", desc: "An Islamic mission organisation in Kenya supporting education facility development as part of its outreach work.", email: "info@bilalmuslimmission.org" },
  { name: "Muslim Aid Kenya", desc: "An Islamic humanitarian organisation in Kenya supporting school infrastructure as part of its relief and development programming.", email: "kenya@muslimaid.org" },
  { name: "Madrasa Early Childhood Programme", desc: "A regional early-childhood education programme supporting Madrasa infrastructure and learning facility development in East Africa.", email: "info@madrasa.org" },
  { name: "ISFD Chad", desc: "An Islamic solidarity development fund supporting education infrastructure projects in Chad.", email: "chad@isfd.org" },
  { name: "Muslim Hands South Africa", desc: "An Islamic humanitarian organisation in South Africa supporting school infrastructure as part of its broader relief programming.", email: "info@muslimhands.org.za" },
  { name: "Islamic Relief South Africa", desc: "The South African chapter of an international Islamic humanitarian organisation, including education infrastructure support in its programming.", email: "info@islamic-relief.org.za" },
  { name: "ICSA South Africa", desc: "An Islamic community organisation in South Africa supporting education facility development.", email: "info@icsa.org.za" },
  { name: "South African Muslim Charitable Trust", desc: "A charitable trust supporting education infrastructure projects within South Africa's Muslim community.", email: "info@samct.org" },
  { name: "Green Masjid Project", desc: "An initiative combining mosque development with community education facility support.", email: "info@greenmasjid.org" },
];

const scholarship: FaithNominee[] = [
  { name: "NASFAT Education Fund", desc: "The education-focused fund of NASFAT, supporting scholarship and bursary access for students within its network.", email: "nasef@nasfat.org" },
  { name: "FOMWAN Scholarship Scheme", desc: "A scholarship scheme run by FOMWAN supporting Muslim girls' and women's access to education.", email: "scholarships@fomwan.org" },
  { name: "MSSN National Scholarship Program", desc: "A nationwide scholarship initiative supporting Muslim students pursuing tertiary education.", email: "scholarships@mssnigeria.org" },
  { name: "Ansar-Ud-Deen Scholarship Board", desc: "A dedicated board administering bursaries and scholarship support for students within the Ansar-Ud-Deen network.", email: "board@auds.org.ng" },
  { name: "Al-Habibiyyah Zakat Scholarship", desc: "A Zakat-funded scholarship initiative supporting students' education costs.", email: "zakat@alhabibiyyah.org" },
  { name: "Islamic Education Trust Initiative", desc: "A scholarship-support initiative under the Islamic Education Trust assisting students with education costs.", email: "scholarships@ietminna.org" },
  { name: "MUSWEN Scholarship Fund", desc: "A bursary fund supporting students within the MUSWEN network.", email: "bursary@muswen.org.ng" },
  { name: "The Muslim Congress Human Capital", desc: "A human-capital development arm of TMC administering scholarships and skills-development support.", email: "human.capital@tmcng.net" },
  { name: "Al-Furqan Foundation Initiative", desc: "A scholarship initiative supporting Islamic studies students.", email: "islamic.scholarships@alfurqan.org" },
  { name: "Jaiz Foundation Support Fund", desc: "An education support fund under Jaiz Foundation assisting students with tuition and education-related costs.", email: "support@jaizfoundation.org.ng" },
  { name: "Aga Khan Foundation", desc: "A development foundation that runs scholarship and education-access programmes as part of its broader portfolio.", email: "scholarships@akf.org" },
  { name: "Alwaleed Islamic Studies Program", desc: "A scholarship programme supporting students pursuing Islamic studies.", email: "scholarships@alwaleedfoundation.org" },
  { name: "Islamic Chamber Scholarships", desc: "A scholarship programme supporting students through the Islamic Chamber of Commerce network.", email: "scholarships@iccm.org" },
  { name: "Islamic Scholarship Fund", desc: "A scholarship fund supporting Muslim students' access to higher education.", email: "director@islamicscholarshipfund.org" },
  { name: "Black Heart Foundation", desc: "A foundation administering scholarships supporting underserved students' education access.", email: "scholarships@blackheartfoundation.org" },
  { name: "Boren Fellowships", desc: "An international fellowship programme supporting language and area-studies education, including in Muslim-majority regions.", email: "scholarships@borenawards.org" },
  { name: "Pan-African Ahmadiyya", desc: "A pan-African Islamic community supporting scholarship access for its members and affiliated students.", email: "scholarships@ahmadiyya.org" },
  { name: "IsDB Scholarships", desc: "The scholarship programme of the Islamic Development Bank, supporting students across member countries.", email: "scholarships@isdb.org" },
  { name: "Muslim World League Orphans", desc: "A scholarship and welfare programme supporting orphaned children's education access.", email: "orphans@mwl.org" },
  { name: "After School Africa Muslim", desc: "An education-access initiative supporting Muslim students' scholarship opportunities across Africa.", email: "muslim@afterschoolafrica.com" },
  { name: "Lisa Maskell Fellowships", desc: "A fellowship programme supporting graduate research, including students from African and Muslim-majority countries.", email: "scholarships@lisamaskell.org" },
  { name: "Al Qasimi Foundation", desc: "A foundation supporting scholarships and education research initiatives.", email: "scholarships@alqasimifoundation.org" },
  { name: "Tahtawi Scholarship", desc: "A scholarship programme supporting students' access to higher education.", email: "scholarships@tahtawi.org" },
  { name: "France Excellence Eiffel", desc: "A French government scholarship programme supporting international students, including from Muslim-majority African countries.", email: "scholarships@franceexcellence.fr" },
  { name: "KAUST Scholarship", desc: "A scholarship programme from a Saudi research university supporting students in STEM fields.", email: "scholarships@kaust.edu.sa" },
  { name: "IDB Education Trust", desc: "An education trust linked to Islamic development financing, supporting scholarship access.", email: "scholarships@idbtrust.org" },
  { name: "IPSA Financial Aid", desc: "A financial-aid programme supporting students' access to education in South Africa.", email: "scholarships@ipsa.co.za" },
  { name: "Deen Arts Foundation", desc: "A foundation supporting scholarships in Islamic arts and education.", email: "scholarships@deenarts.org" },
  { name: "1 Million Scholarship Project", desc: "A large-scale scholarship initiative supporting students' access to education.", email: "director@1millionscholarship.org" },
  { name: "Bursary Africa Muslims Agency", desc: "A bursary programme supporting Muslim students' education access across Africa.", email: "scholarships@bursaryafrica.org" },
];

const holistic: FaithNominee[] = [
  { name: "FOMWAN National Education Program", desc: "A national programme combining education access with girl-child welfare support under FOMWAN.", email: "girlchild@fomwan.org" },
  { name: "NASFAT Agency for Zakat", desc: "The Zakat-distribution arm of NASFAT, channelling Zakat funds toward holistic learner support including education-linked welfare assistance.", email: "nazas@nasfat.org" },
  { name: "Ansar-Ud-Deen Education Directorate", desc: "A directorate coordinating holistic school support programmes within the Ansar-Ud-Deen network.", email: "education@auds.org.ng" },
  { name: "MSSN Schools Outreach", desc: "An outreach programme combining school support with broader community education engagement.", email: "outreach@mssnigeria.org" },
  { name: "The Muslim Congress Education Directorate", desc: "A directorate overseeing education development programming for affiliated institutions.", email: "education@tmcng.net" },
  { name: "Islamic Education Trust School Support", desc: "A school support arm providing wraparound assistance to schools in the Trust's network.", email: "schools@ietminna.org" },
  { name: "MUSWEN Education Development", desc: "An education development unit supporting holistic school improvement initiatives.", email: "development@muswen.org.ng" },
  { name: "Al-Habibiyyah Project Eat-Learn-Play", desc: "A combined nutrition-and-education programme pairing meals with learning support for children.", email: "eatlearnplay@alhabibiyyah.org" },
  { name: "Rahma Islamic Foundation Outreach", desc: "An Islamic foundation supporting holistic welfare and education outreach.", email: "outreach@rahmaww.org" },
  { name: "Zakat & Sadaqat Foundation Aid", desc: "A Zakat and Sadaqat-funded foundation supporting holistic education and welfare aid.", email: "aid@zakatandsadaqat.org.ng" },
  { name: "Al-Kisa Foundation", desc: "A foundation providing holistic education and welfare support to underserved communities.", email: "info@alkisa.org" },
  { name: "Islamic Relief Ethiopia", desc: "The Ethiopia country programme of Islamic Relief, combining education support with broader humanitarian and development assistance.", email: "info@islamic-relief.org.et" },
  { name: "Maqasid Institute", desc: "An institute combining Islamic scholarship with broader social and educational development programming.", email: "info@maqasidinstitute.org" },
  { name: "Maydan Islamic Centers", desc: "A network of Islamic centres providing holistic community and education support.", email: "info@maydan.org" },
  { name: "Annur Center", desc: "An Islamic centre providing combined education and community welfare support.", email: "info@annurcenter.org" },
  { name: "Islamic Education Trust", desc: "A trust supporting holistic education programming combining curriculum, facility, and learner welfare support.", email: "info@ietonline.org" },
  { name: "Holistic Trust", desc: "A trust supporting holistic education and welfare programming.", email: "info@holistictrust.org" },
  { name: "Ummah for Earth", desc: "An initiative combining environmental and educational awareness within Muslim communities.", email: "info@ummahfors.org" },
  { name: "Islamic Ummah Relief", desc: "A relief organisation combining education support with broader humanitarian assistance.", email: "info@islamicummahrelief.org" },
  { name: "Bilal Muslim Mission", desc: "An Islamic mission organisation combining education support with community outreach.", email: "info@bilalmuslimmission.org" },
  { name: "Taawanu Islamic Foundation", desc: "A foundation supporting holistic education and welfare programming for underserved communities.", email: "info@taawanu.org" },
  { name: "Inclusive Education IRW Kenya", desc: "An inclusive-education programme under Islamic Relief Worldwide Kenya, supporting learners with additional needs.", email: "info@irwkenya.org" },
  { name: "IIIT East Africa", desc: "A regional Islamic research and education institute supporting holistic academic development in East Africa.", email: "info@iiiteastafrica.org" },
  { name: "MEWA Muslim Education", desc: "An organisation supporting holistic Muslim education and welfare programming.", email: "info@mewamuslim.org" },
  { name: "Muslim Hands Education", desc: "The education arm of an international Islamic humanitarian organisation, supporting school access alongside broader humanitarian assistance.", email: "education@muslimhands.org" },
  { name: "Islamic Dawah Movement", desc: "A movement combining religious outreach with community education and welfare support.", email: "info@islamicdawah.org" },
  { name: "MASA Muslim Association", desc: "A Muslim association supporting holistic education and community welfare programming.", email: "info@masamuslim.org" },
  { name: "IEOSA", desc: "An Islamic education organisation supporting holistic learner welfare and academic support.", email: "info@ieosa.org" },
  { name: "Islamia College", desc: "An Islamic educational institution combining academic and holistic student support.", email: "info@islamiacollege.org" },
  { name: "WAMY", desc: "The World Assembly of Muslim Youth, supporting holistic youth education and development programming internationally.", email: "info@wamy.org" },
];

const advocacy: FaithNominee[] = [
  { name: "NASFAT Health & Education Advocacy Unit", desc: "An advocacy unit within NASFAT engaging in public education and health-awareness campaigns.", email: "advocacy@nasfat.org" },
  { name: "FOMWAN National Education Advocacy Wing", desc: "The advocacy wing of FOMWAN campaigning on education policy issues affecting Muslim women and girls.", email: "advocacy@fomwan.org" },
  { name: "Ansar-Ud-Deen Awareness & Public Enlightenment Bureau", desc: "A bureau running public enlightenment and awareness campaigns, including on education access.", email: "enlightenment@auds.org.ng" },
  { name: "MSSN Advocacy & Policy Unit", desc: "A policy and advocacy unit engaging with education policy issues affecting Muslim students.", email: "policy@mssnigeria.org" },
  { name: "The Muslim Congress Da'wah & Education Policy Advocacy", desc: "An advocacy arm combining religious outreach with engagement on education policy issues.", email: "dawah@tmcng.net" },
  { name: "Islamic Education Trust Public Enlightenment Programs", desc: "Public awareness programming run by the Trust to promote education access and quality.", email: "enlightenment@ietminna.org" },
  { name: "MUSWEN Policy & Interfaith Education Dialogue", desc: "A dialogue and policy engagement initiative addressing education issues across faith communities.", email: "policy@muswen.org.ng" },
  { name: "Al-Furqan Foundation Public Awareness Campaigns", desc: "Public awareness campaigns run by the foundation on Islamic and general education access.", email: "campaigns@alfurqan.org" },
  { name: "Al-Habibiyyah Inter-faith Educational Dialogue Forums", desc: "Interfaith dialogue forums addressing shared education access and policy issues.", email: "interfaith@alhabibiyyah.org" },
  { name: "Islamic Society of Nigeria Education Reform Advocacy", desc: "The umbrella body for Islamic affairs in Nigeria, engaging in advocacy on education policy and reform issues affecting Muslim communities.", email: "reform@nscia.com.ng" },
  { name: "Global Muslim Advocacy Groups", desc: "International advocacy networks engaging on education access issues affecting Muslim communities globally.", email: "info@globalmuslimadvocacy.org" },
  { name: "Islamic Relief", desc: "The advocacy arm of Islamic Relief Worldwide, campaigning on education access issues alongside its humanitarian programming.", email: "advocacy@islamic-relief.org" },
  { name: "UNICEF (Muslim partners)", desc: "UNICEF's faith-engagement programming, partnering with Muslim communities on education advocacy and awareness.", email: "muslim@unicef.org" },
  { name: "UNESCO (Muslim partners)", desc: "UNESCO's faith-engagement programming, partnering with Muslim communities on education advocacy and awareness.", email: "muslim@unesco.org" },
  { name: "Room to Read", desc: "An international literacy organisation advocating for education access and reading programmes.", email: "nigeria@roomtoread.org" },
  { name: "Global Partnership for Education", desc: "A multilateral education partnership engaging in advocacy for education financing and access globally.", email: "advocacy@globalpartnership.org" },
  { name: "Alwaleed Philanthropies", desc: "A philanthropic foundation engaging in advocacy and awareness campaigns on education access.", email: "advocacy@alwaleedphilanthropies.org" },
  { name: "Dubai Cares", desc: "A global education philanthropy advocating for children's access to quality education, including in Muslim-majority countries.", email: "advocacy@dubaicares.ae" },
  { name: "King Khalid Foundation", desc: "A Saudi philanthropic foundation engaging in advocacy on education and social development issues.", email: "advocacy@kkf.org.sa" },
  { name: "Forum for African Women Educationalists", desc: "A pan-African network advocating for girls' education access and policy reform across the continent.", email: "advocacy@fawe.org" },
  { name: "African Council for Communication Education", desc: "A regional council advocating for communication and education reform across Africa.", email: "info@acceafrica.org" },
  { name: "African Development and Advocacy Centre", desc: "A centre engaging in development and education-policy advocacy across Africa.", email: "advocacy@adac.org" },
  { name: "Islamic Institutions in Arab States", desc: "A coalition of Islamic institutions advocating for education reform across Arab states.", email: "director@islamicinstitutions.org" },
  { name: "Carnegie Arab Education", desc: "A research-and-advocacy programme engaging on education reform issues in the Arab world.", email: "education@carnegie-mec.org" },
  { name: "ECOWAS Islamic Scholars", desc: "A regional network of Islamic scholars engaging in education-policy advocacy across West Africa.", email: "director@ecowasislamicscholars.org" },
  { name: "ECOWAS OIC Quranic", desc: "A regional body coordinating Quranic education advocacy across ECOWAS member states.", email: "quranic@ecowasoic.org" },
  { name: "Ansar Ud Deen", desc: "An Islamic society engaging in education advocacy alongside its broader community programming.", email: "advocacy@ansaruddeen.org" },
  { name: "MSSN Advocacy", desc: "The advocacy arm of the Muslim Students Society of Nigeria, engaging on education policy issues.", email: "advocacy@mssnigeria.org" },
  { name: "Muslim Congress Da'wah", desc: "The da'wah and outreach arm of The Muslim Congress, combining religious outreach with education advocacy.", email: "dawah@tmcng.net" },
  { name: "Islamic Education Trust Programs", desc: "Public enlightenment and advocacy programming run by the Islamic Education Trust.", email: "enlightenment@ietminna.org" },
];

export const islamicEducationConfig: FaithCategoryConfig = {
  faith: "islamic",
  routePath: "/categories/islamic-education-impact-africa",
  pageTitle: "Excellence in Islamic Education Impact (Africa Regional)",
  pageSubheading: "Honoring Islamic impact on education across the African continent",
  primaryNominateUuid: "b1b19333-917c-4ab5-b5e4-4bb9f5d7e4e2",
  subcategories: [
    { title: "Best Educational Infrastructure Development", description: "Islamic organisations building, equipping, or rehabilitating schools and learning facilities across Africa.", uuid: "b1b19333-917c-4ab5-b5e4-4bb9f5d7e4e2", tabKey: "infrastructure" },
    { title: "Best Scholarship Program", description: "Islamic organisations funding tuition, bursaries, or scholarship pathways for learners.", uuid: "c97afbc4-719e-42fa-b483-3964a30d21b2", tabKey: "scholarship" },
    { title: "Best Holistic Educational Support", description: "Islamic organisations combining education with health, nutrition, or wraparound learner support.", uuid: "3ca340f2-80a8-4ae7-a7a9-eb771ac3eb52", tabKey: "holistic" },
    { title: "Best Advocacy for Educational Reforms & Awareness Campaigns", description: "Islamic organisations campaigning for education policy reform, access, and public awareness.", uuid: "4ded4d21-b068-4c51-9193-09c809722961", tabKey: "advocacy" },
  ],
  overviewParagraphs: ["Islamic educational traditions have shaped learning across Africa for over a millennium — from the scholarly centres of Timbuktu and Al-Azhar's African alumni networks to the Madrasah and Islamiyya systems that educate millions of children today.", "Excellence in Islamic Education Impact (Africa Regional) recognises schools and institutions, scholarship programmes, holistic education support, and advocacy organisations whose sustained programmes advance literacy, Quranic learning, and integrated education across the continent. Institutional recognition is evaluated under governance and leadership criteria, aligned with SDG 4, SDG 17, and Africa Agenda 2063 Goal 1.", "This recognition is continental in scope: an institution's contribution is assessed by its impact across Africa as a whole, not confined to a single country."],
  whoQualifies: ["Madrasah, Quranic, and Islamiyya schools", "Islamic education NGOs and foundations", "Islamic scholarship and bursary programmes", "Islamic organisations providing holistic education and welfare support", "Advocacy organisations campaigning for Islamic education reform and awareness", "Waqf and endowment-based education funders"],
  ediTable: [{"area": "Evidence Quality", "score": 20, "what": "Official records, government recognition, verified enrolment data"}, {"area": "Education Access", "score": 15, "what": "Learners reached, out-of-school children supported, scholarships"}, {"area": "Learning Quality", "score": 15, "what": "Quranic and Islamic studies curricula, integrated formal subjects, teacher training"}, {"area": "Equity & Inclusion", "score": 15, "what": "Girls' access, rural learners, low-income students, refugees"}, {"area": "Scale & Reach", "score": 10, "what": "Number of schools, countries, learners, institutions"}, {"area": "Sustainability", "score": 10, "what": "Waqf endowment structure, government partnership, institutional continuity"}, {"area": "Innovation", "score": 10, "what": "Curriculum integration models, digital Quranic learning, teacher certification"}, {"area": "Story / Documentary Value", "score": 5, "what": "Human-interest story, visible impact, testimonials"}],
  evidenceNote: "To move a nominee from Pending Verification to Accepted, submit at least 3 of: an official institution page, government or community endorsement, enrolment/beneficiary numbers, photos/video of delivery, founding or endowment documentation, a beneficiary testimonial, or independent media coverage. Accepted organisations receive a private link to complete their full public profile, including logo, self-reported description, years active, and beneficiary figures. Only organisational contact details are published before profile completion — individual staff contacts are never made public without separate written consent.",
  recognitionPackage: [
    "Platinum Digital Certificate (GFA Wallet)",
    "Letter of Recognition from SCEF / NESA-Africa",
    "Feature spotlight on NESA TV",
    "Listing in the Islamic Education Partners database under SCEF",
    "Private profile edit link to publish logo, description, years active, and beneficiary figures",
  ],
  faqEvidence: "At least 3 of: institution page, government/community endorsement, enrolment data, photos/video, endowment or founding documents, testimonial, or media coverage.",
  tabs: {
    infrastructure,
    scholarship,
    holistic,
    advocacy,
  },
};
