import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  Briefcase,
  Radio,
  Users,
  Camera,
  Code2,
  Building2,
  ShieldCheck,
  Megaphone,
  MapPin,
  BookOpen,
  Sparkles,
  Calendar,
} from "lucide-react";

type ContentAngle = {
  moment: string;
  channel: string;
  monetization: string;
};

type Vacancy = {
  id: string;
  code: string;
  title: string;
  org: "NESA-Africa" | "EduAid-Africa";
  publicFacing: boolean;
  summary: string;
  icon: React.ComponentType<{ className?: string }>;
  content?: ContentAngle;
  priority?: "P1" | "P2";
};

const VACANCIES: Vacancy[] = [
  {
    id: "governance-compliance",
    code: "N-01",
    title: "Governance & Compliance Officer",
    org: "NESA-Africa",
    publicFacing: false,
    icon: ShieldCheck,
    summary:
      "Owns NRC and jury governance policy, non-influence protocol, audit trail. Standard confidential hire — not a public recruitment moment.",
  },
  {
    id: "executive-operations-admin",
    code: "N-02",
    title: "Executive & Operations Administrator",
    org: "NESA-Africa",
    publicFacing: false,
    icon: Briefcase,
    summary:
      "Coordinates SCEF board scheduling, official correspondence, cycle operations. Standard back-office hire.",
  },
  {
    id: "fullstack-developer",
    code: "N-03",
    title: "Full-Stack Platform Developer",
    org: "NESA-Africa",
    publicFacing: true,
    icon: Code2,
    summary:
      "Ships features on the NESA-Africa platform (React + Lovable Cloud stack).",
    content: {
      moment:
        "\"Build With Us\" — a livestreamed or recorded technical challenge / portfolio review used as the actual interview stage.",
      channel: "Social media + NESA Africa TV",
      monetization:
        "Technology sponsor (fintech / cloud provider) sponsors the segment — direct fit with the existing Technology Partnership category.",
    },
  },
  {
    id: "product-delivery-manager",
    code: "N-04",
    title: "Product & Delivery Manager",
    org: "NESA-Africa",
    publicFacing: false,
    icon: Briefcase,
    summary:
      "Owns cycle delivery, ships against the 2026 timeline. Standard hire; reasoning may feed a \"Behind the Build\" content thread but the interview itself is not filmable.",
  },
  {
    id: "data-engineer-nrc",
    code: "N-05",
    title: "Data Engineer / NRC Systems Analyst",
    org: "NESA-Africa",
    publicFacing: false,
    icon: ShieldCheck,
    summary:
      "Runs the NRC dossier pipeline, duplicate detection, EDI scoring integrity. Confidentiality of NRC precludes public treatment.",
  },
  {
    id: "bd-partnerships-lead",
    code: "N-06",
    title: "Business Development & Partnerships Lead",
    org: "NESA-Africa",
    publicFacing: false,
    icon: Briefcase,
    summary:
      "Manages sponsor pipeline, endorsement partners, institutional relationships — including the sponsorships generated by the public-facing recruitment moments below.",
  },
  {
    id: "content-social-producer",
    code: "N-07",
    title: "Content, Social Media & Design Producer",
    org: "NESA-Africa",
    publicFacing: true,
    priority: "P1",
    icon: Sparkles,
    summary:
      "Runs the daily content engine — posts, motion graphics, cycle campaign design.",
    content: {
      moment:
        "Public \"audition\": candidates submit a real sample post or design for an actual upcoming NESA-Africa need; the strongest entries get featured before the hire is made.",
      channel: "Social media reveal (Instagram / TikTok format), cross-posted to NESA Africa TV",
      monetization:
        "The recruitment itself IS the growth engine — this role's own hiring process becomes proof-of-work content; no separate sponsor needed to justify it.",
    },
  },
  {
    id: "media-presenter",
    code: "N-08",
    title: "Media Production & On-Air Presenter",
    org: "NESA-Africa",
    publicFacing: true,
    priority: "P1",
    icon: Radio,
    summary:
      "Hosts webinar series, TV award show segments, and Gala coverage.",
    content: {
      moment:
        "A real televised audition / casting call — the \"TV Presenters Needed\" format run as an on-air segment instead of a quiet job listing.",
      channel: "NESA Africa TV + one dedicated Webinar Series or TV Award Show segment",
      monetization:
        "Presenter-search segment is a natural sponsorship slot — matches the existing Webinar Series episode-sponsorship model (Pathway 4a).",
    },
  },
  {
    id: "chapter-ambassador-coordinator",
    code: "N-09",
    title: "Local Chapter & Ambassador Coordinator",
    org: "NESA-Africa",
    publicFacing: true,
    priority: "P1",
    icon: MapPin,
    summary:
      "Activates the 8 African regional chapters and ambassador network.",
    content: {
      moment:
        "Regional \"Meet Your Chapter\" content — each African region gets a short feature once its Coordinator is hired, tying into the Regions page and Local Chapters build.",
      channel: "Social media + the Regions page",
      monetization:
        "Regional sponsor (bank, telecom) sponsors a specific region's chapter launch content — matches Gold-Blue Garnet CSR category sponsors already in the outreach pipeline.",
    },
  },
  {
    id: "nrc-reviewer",
    code: "N-10",
    title: "Nominee Research Corps Reviewer",
    org: "NESA-Africa",
    publicFacing: false,
    icon: ShieldCheck,
    summary:
      "Verifies nominee evidence, runs dossier scoring inside the NRC firewall. Independence and confidentiality by design — no public treatment.",
  },
  {
    id: "gala-events-lead",
    code: "N-11",
    title: "Gala & Event Operations Lead",
    org: "NESA-Africa",
    publicFacing: true,
    priority: "P2",
    icon: Camera,
    summary:
      "Owns Gala production, run-of-show, on-site event operations.",
    content: {
      moment:
        "\"Countdown to the Gala\" behind-the-scenes production content once hired.",
      channel: "NESA Africa TV + social",
      monetization:
        "Natural tie-in to existing Gala ticket sales and sponsorship — not a separate revenue stream.",
    },
  },
  {
    id: "eduaid-rebuild-lead",
    code: "EA-1",
    title: "Rebuild My School Africa — Programme Launch Lead",
    org: "EduAid-Africa",
    publicFacing: true,
    priority: "P2",
    icon: Building2,
    summary:
      "Leads the Rebuild My School Africa programme — school selection, community engagement, rebuild delivery.",
    content: {
      moment:
        "Once hired, the school-selection and rebuild process is inherently visual, strong content — but runs on EduAid-Africa's own channel, not NESA-Africa's, per the platform firewall.",
      channel: "EduAid-Africa's own platform",
      monetization:
        "CSR sponsor of the specific school / region being rebuilt — applies EduAid-Africa's existing CSR Fund Management model to content.",
    },
  },
  {
    id: "eduaid-journal-lead",
    code: "EA-2",
    title: "Education Journal / Publications Lead",
    org: "EduAid-Africa",
    publicFacing: false,
    icon: BookOpen,
    summary:
      "Owns the EduAid-Africa Education White Paper and Journal. Its output is its own distribution vehicle — not additional video content.",
    content: {
      moment:
        "Not a visual / video role — the White Paper is the deliverable and the distribution vehicle.",
      channel: "EduAid-Africa's own platform",
      monetization:
        "Institutional / knowledge-partner sponsorship of the Journal itself, distinct from video monetization.",
    },
  },
];

const CALENDAR = [
  { window: "20 Aug – 12 Nov 2026", label: "Pre-Award Webinar Series", tie: "Presenter-search episode (N-08); Build-With-Us segment (N-03)." },
  { window: "28 Nov 2026", label: "TV Award Show — Recognition Ratification", tie: "Chapter Coordinator regional features (N-09) roll out ahead of broadcast." },
  { window: "6 Dec 2026", label: "TV Award Show — Icon Class Reveal", tie: "Content Producer (N-07) audition reveal published in campaign runway." },
  { window: "13 Dec 2026", label: "NESA-Africa Recognition Gala, Lagos", tie: "Gala & Events Lead (N-11) \"Countdown to the Gala\" behind-the-scenes." },
];

function VacancyCard({ v }: { v: Vacancy }) {
  const Icon = v.icon;
  return (
    <motion.article
      initial={{ opacity: 0, y: 12 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="rounded-2xl border border-gold/20 bg-charcoal/60 p-6 hover:border-gold/50 transition-colors"
    >
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="flex items-center gap-3">
          <span className="w-10 h-10 rounded-lg bg-gold/10 border border-gold/30 flex items-center justify-center">
            <Icon className="w-5 h-5 text-gold" />
          </span>
          <div>
            <div className="text-[11px] uppercase tracking-[0.16em] text-gold/80">
              {v.code} · {v.org}
            </div>
            <h3 className="font-display text-lg text-ivory leading-tight">{v.title}</h3>
          </div>
        </div>
        {v.priority && (
          <span className="text-[10px] uppercase tracking-[0.14em] px-2 py-1 rounded-full border border-gold/40 text-gold">
            Priority {v.priority}
          </span>
        )}
      </div>

      <p className="text-sm text-ivory/70 mb-4">{v.summary}</p>

      {v.content ? (
        <div className="space-y-2 text-sm border-t border-gold/10 pt-4">
          <div>
            <span className="text-gold/80 font-semibold">Filmable moment: </span>
            <span className="text-ivory/80">{v.content.moment}</span>
          </div>
          <div>
            <span className="text-gold/80 font-semibold">Channel: </span>
            <span className="text-ivory/80">{v.content.channel}</span>
          </div>
          <div>
            <span className="text-gold/80 font-semibold">Monetization: </span>
            <span className="text-ivory/80">{v.content.monetization}</span>
          </div>
        </div>
      ) : (
        <div className="text-xs text-ivory/50 border-t border-gold/10 pt-4 italic">
          Standard confidential hire — no public recruitment content.
        </div>
      )}
    </motion.article>
  );
}

export default function Vacancies() {
  const publicRoles = VACANCIES.filter((v) => v.publicFacing);
  const standardRoles = VACANCIES.filter((v) => !v.publicFacing);

  return (
    <>
      <Helmet>
        <title>Vacancies · NESA-Africa & EduAid-Africa</title>
        <meta
          name="description"
          content="13 standing vacancies across NESA-Africa (11) and EduAid-Africa (2). Public-facing roles are recruited as content moments on NESA Africa TV, the Webinar Series and social — sequenced against the 2026 calendar."
        />
        <link rel="canonical" href="https://nesa.africa/vacancies" />
      </Helmet>

      <section className="bg-charcoal border-b border-gold/15">
        <div className="container mx-auto px-4 py-14 md:py-20">
          <span className="text-[11px] uppercase tracking-[0.2em] text-gold font-semibold">
            Recruitment as growth engine
          </span>
          <h1 className="font-display text-3xl md:text-5xl font-bold text-ivory mt-2 mb-4">
            13 Standing Vacancies
          </h1>
          <p className="text-ivory/70 max-w-3xl text-base md:text-lg">
            Eleven NESA-Africa roles and two EduAid-Africa roles. Where the role is public-facing
            by nature, the recruitment process itself runs as scheduled content on channels
            already established — the Webinar Series, NESA Africa TV, the TV Award Shows and
            social. Governance, NRC, Data and BD hires remain standard confidential processes.
          </p>
          <div className="mt-6 flex flex-wrap gap-3 text-xs">
            <span className="px-3 py-1 rounded-full border border-gold/30 text-gold/90">
              3 Priority-1 public roles
            </span>
            <span className="px-3 py-1 rounded-full border border-ivory/20 text-ivory/70">
              5 standard confidential hires
            </span>
            <span className="px-3 py-1 rounded-full border border-ivory/20 text-ivory/70">
              Sequenced against 2026 calendar
            </span>
          </div>
        </div>
      </section>

      <section className="bg-charcoal py-14">
        <div className="container mx-auto px-4">
          <h2 className="font-display text-2xl md:text-3xl text-ivory mb-2">
            Public-facing roles — recruited as content
          </h2>
          <p className="text-ivory/60 text-sm mb-8 max-w-2xl">
            Priority-1 roles (Content Producer, On-Air Presenter, Chapter Coordinator) run first — their
            actual job is public-facing, so the recruitment doubles as real content rather than performative content.
          </p>
          <div className="grid md:grid-cols-2 gap-5">
            {publicRoles.map((v) => (
              <VacancyCard key={v.id} v={v} />
            ))}
          </div>
        </div>
      </section>

      <section className="bg-charcoal/95 py-14 border-t border-gold/10">
        <div className="container mx-auto px-4">
          <h2 className="font-display text-2xl md:text-3xl text-ivory mb-2 flex items-center gap-2">
            <Calendar className="w-6 h-6 text-gold" /> Sequenced against the 2026 calendar
          </h2>
          <p className="text-ivory/60 text-sm mb-8 max-w-2xl">
            Recruitment moments align to the fixtures already locked, not a separate unscheduled activity.
          </p>
          <div className="space-y-3">
            {CALENDAR.map((c) => (
              <div
                key={c.window}
                className="rounded-xl border border-gold/15 bg-charcoal/60 p-4 md:flex md:items-start md:gap-6"
              >
                <div className="md:w-64 shrink-0">
                  <div className="text-gold font-semibold text-sm">{c.window}</div>
                  <div className="text-ivory/90 text-sm">{c.label}</div>
                </div>
                <div className="text-ivory/70 text-sm mt-2 md:mt-0">{c.tie}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-charcoal py-14 border-t border-gold/10">
        <div className="container mx-auto px-4">
          <h2 className="font-display text-2xl md:text-3xl text-ivory mb-2 flex items-center gap-2">
            <Users className="w-6 h-6 text-gold" /> Standard confidential hires
          </h2>
          <p className="text-ivory/60 text-sm mb-8 max-w-2xl">
            Governance, NRC, Data, BD and back-office operations — no public content treatment.
            Forcing one on would be manufactured rather than real.
          </p>
          <div className="grid md:grid-cols-2 gap-5">
            {standardRoles.map((v) => (
              <VacancyCard key={v.id} v={v} />
            ))}
          </div>
        </div>
      </section>

      <section className="bg-charcoal/95 py-14 border-t border-gold/10">
        <div className="container mx-auto px-4 max-w-3xl">
          <div className="rounded-2xl border border-gold/25 bg-gold/5 p-6">
            <h3 className="font-display text-xl text-ivory mb-3 flex items-center gap-2">
              <Megaphone className="w-5 h-5 text-gold" /> Honest baseline
            </h3>
            <p className="text-ivory/75 text-sm leading-relaxed">
              No follower or revenue numbers are projected on this page. Until roles N-07 and N-08
              are filled and a first audition piece is actually published, there is no baseline to
              project growth or revenue from. The strongest single pilot is N-08's on-air
              presenter search — a format the organization has already run — measured against a
              real baseline before extending the model to the other public-facing roles.
            </p>
          </div>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link
              to="/contact"
              className="inline-flex items-center gap-2 rounded-lg bg-gold text-charcoal px-5 py-3 text-sm font-semibold hover:bg-gold/90 transition"
            >
              Apply or express interest
            </Link>
            <Link
              to="/volunteer"
              className="inline-flex items-center gap-2 rounded-lg border border-gold/40 text-ivory px-5 py-3 text-sm font-semibold hover:border-gold transition"
            >
              Prefer to volunteer instead →
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
