import type { AwardCategoryConfig } from "./types";
import { buildStandardFaqs } from "./faqBuilder";

const G = "blue_garnet" as const;
const PARENT = "/awards/blue-garnet-categories";
const url = (slug: string) => `${PARENT}/${slug}`;

export const BLUE_GARNET_CATEGORIES: AwardCategoryConfig[] = [
  {
    slug: "ngo-education-africa",
    finalName: "Best NGO Contribution to Education (Africa)",
    group: G,
    url: url("ngo-education-africa"),
    parentPage: PARENT,
    shortDescription:
      "Honouring NGOs across Africa driving educational access, equity, infrastructure and community impact at continental scale.",
    eligibilitySummary:
      "Registered NGOs operating in two or more African countries with verifiable education-focused programmes in the last 3 years.",
    whoCanBeNominated: "Registered non-profit organisations with cross-border or pan-African education programmes.",
    whoCanNominate: "The public, peers, partners and self-nomination — all subject to NRC verification.",
    requiredEvidence: [
      "Registration certificate(s)",
      "Programme reports for last 2 cycles",
      "Beneficiary impact data with citations",
      "Audited financials or recognised partner attestation",
    ],
    reviewMethod: "NRC eligibility → jury shortlist → public vote (Blue Garnet formula) → winner.",
    votingRole: "Public voting — counts towards Blue Garnet final score.",
    judgingRole: "Independent jury shortlist + final scoring.",
    relatedCategories: ["ngo-education-nigeria", "csr-education-africa", "edutech-africa"],
    seoTitle: "Best NGO Contribution to Education (Africa) | NESA-Africa 2026",
    metaDescription:
      "Vote and nominate the African NGOs driving education access, equity and community impact across the continent.",
    faqs: buildStandardFaqs({
      eligibility: "Registered NGOs with active education programmes in 2+ African countries within the last 3 years.",
      whoCanNominate: "Anyone — public, peers, beneficiaries, partners, or self-nomination. All entries pass NRC review.",
      evidence: "Registration, programme reports, beneficiary data with citations, and financial attestation.",
      publicVoting: "Yes. Public voting opens after the jury shortlist and counts towards the final Blue Garnet score.",
      review: "Three stages: NRC verification, independent jury shortlist, then a combined public vote + final jury score.",
    }),
    legacyComponentKey: "NGOEducationAfrica",
    mergedFrom: ["/categories/ngo-africa", "/category/ngo-education-africa"],
  },
  {
    slug: "ngo-education-nigeria",
    finalName: "Best NGO Contribution to Education (Nigeria)",
    group: G,
    url: url("ngo-education-nigeria"),
    parentPage: PARENT,
    shortDescription: "Recognising Nigerian NGOs unlocking education access, equity and opportunity nationwide.",
    eligibilitySummary: "Registered Nigerian NGOs with verifiable education programmes in the last 3 years.",
    whoCanBeNominated: "CAC-registered non-profits operating education programmes within Nigeria.",
    whoCanNominate: "Public, peers, beneficiaries, partners, or self-nomination.",
    requiredEvidence: [
      "CAC registration",
      "Programme reports",
      "Beneficiary impact data with citations",
      "Financial attestation",
    ],
    reviewMethod: "NRC eligibility → jury shortlist → public vote → final score.",
    votingRole: "Public voting — Blue Garnet weighted formula.",
    judgingRole: "Jury shortlist and final scoring.",
    relatedCategories: ["ngo-education-africa", "csr-education-nigeria", "media-advocacy-nigeria"],
    seoTitle: "Best NGO Contribution to Education (Nigeria) | NESA-Africa 2026",
    metaDescription: "Vote and nominate Nigerian NGOs transforming education access, equity and community impact.",
    faqs: buildStandardFaqs({
      eligibility: "CAC-registered Nigerian NGOs with active education programmes in the last 3 years.",
      whoCanNominate: "Anyone, subject to NRC verification.",
      evidence: "CAC registration, programme reports, beneficiary data, and financial attestation.",
      publicVoting: "Yes — Blue Garnet competitive track.",
      review: "NRC verification, jury shortlist, then public vote + final jury score combined.",
    }),
    legacyComponentKey: "NGOEducationNigeria",
    mergedFrom: ["/categories/ngo-nigeria", "/category/ngo-education-nigeria"],
  },
  {
    slug: "csr-education-africa",
    finalName: "Best CSR in Education (Africa)",
    group: G,
    url: url("csr-education-africa"),
    parentPage: PARENT,
    shortDescription:
      "Celebrating African corporates channelling CSR into scholarships, infrastructure and lasting education impact across multiple countries.",
    eligibilitySummary: "Companies with documented education-focused CSR in 2+ African countries over the last 3 years.",
    whoCanBeNominated: "Public or private companies headquartered or operating in Africa with verifiable cross-border CSR.",
    whoCanNominate: "Anyone, including beneficiaries and partners. Self-nomination permitted with full disclosure.",
    requiredEvidence: [
      "CSR programme reports or sustainability reports",
      "Beneficiary numbers with citations",
      "Partner attestations",
      "Spend verification (audited or attested)",
    ],
    reviewMethod: "NRC eligibility → jury shortlist → public vote → final score.",
    votingRole: "Public voting — Blue Garnet weighted.",
    judgingRole: "Jury shortlist and final scoring.",
    relatedCategories: ["csr-education-nigeria", "ngo-education-africa", "edutech-africa"],
    seoTitle: "Best CSR in Education (Africa) | NESA-Africa 2026",
    metaDescription:
      "Vote and nominate African corporates whose CSR is reshaping education access and outcomes continent-wide.",
    faqs: buildStandardFaqs({
      eligibility: "Companies with documented education CSR in 2+ African countries within the last 3 years.",
      whoCanNominate: "Public, partners, beneficiaries, or self-nomination with disclosure.",
      evidence: "CSR/sustainability reports, beneficiary data with citations, partner attestations, spend verification.",
      publicVoting: "Yes — Blue Garnet competitive track.",
      review: "NRC verification, independent jury shortlist, then public vote + jury final score.",
    }),
    legacyComponentKey: "CSREducationAfrica",
    mergedFrom: ["/categories/csr-africa", "/categories/csr", "/awards/csr-education", "/awards/csr-for-education"],
  },
  {
    slug: "csr-education-nigeria",
    finalName: "Best CSR in Education (Nigeria)",
    group: G,
    url: url("csr-education-nigeria"),
    parentPage: PARENT,
    shortDescription:
      "Honouring Nigerian corporates channelling CSR into scholarships, infrastructure, teacher development and innovation.",
    eligibilitySummary: "Nigerian-registered companies with documented education CSR in the last 3 years.",
    whoCanBeNominated: "CAC-registered companies operating in Nigeria.",
    whoCanNominate: "Public, partners, beneficiaries, or self-nomination with disclosure.",
    requiredEvidence: [
      "CSR or sustainability reports",
      "Beneficiary data with citations",
      "Partner attestations",
      "Spend verification",
    ],
    reviewMethod: "NRC eligibility → jury shortlist → public vote → final score.",
    votingRole: "Public voting — Blue Garnet weighted.",
    judgingRole: "Jury shortlist and final scoring.",
    relatedCategories: ["csr-education-africa", "ngo-education-nigeria", "education-state-nigeria"],
    seoTitle: "Best CSR in Education (Nigeria) | NESA-Africa 2026",
    metaDescription:
      "Vote and nominate the Nigerian corporates whose CSR is delivering measurable impact in education.",
    faqs: buildStandardFaqs({
      eligibility: "CAC-registered companies with documented education CSR within the last 3 years.",
      whoCanNominate: "Anyone, subject to NRC verification.",
      evidence: "CSR/sustainability reports, beneficiary data, partner attestations, spend verification.",
      publicVoting: "Yes — Blue Garnet competitive track.",
      review: "NRC verification, jury shortlist, then public vote + jury final score.",
    }),
    legacyComponentKey: "CSREducationNigeria",
    mergedFrom: ["/categories/csr-nigeria", "/category/csr-education-nigeria"],
  },
  {
    slug: "edutech-africa",
    finalName: "Best EduTech Organisation (Africa)",
    group: G,
    url: url("edutech-africa"),
    parentPage: PARENT,
    shortDescription:
      "Celebrating EduTech companies digitising African learning — platforms, apps and innovation transforming education.",
    eligibilitySummary: "EduTech organisations serving learners across one or more African markets.",
    whoCanBeNominated: "For-profit or non-profit EduTech organisations with verifiable African user base.",
    whoCanNominate: "Anyone, including users and partners.",
    requiredEvidence: [
      "Product description and country coverage",
      "Verified active-user metrics",
      "Learning outcome evidence",
      "Partnership or institutional attestation",
    ],
    reviewMethod: "NRC eligibility → jury shortlist → public vote → final score.",
    votingRole: "Public voting — Blue Garnet weighted.",
    judgingRole: "Jury shortlist and final scoring.",
    relatedCategories: ["stem-education-africa", "csr-education-africa", "ngo-education-africa"],
    seoTitle: "Best EduTech Organisation (Africa) | NESA-Africa 2026",
    metaDescription:
      "Vote and nominate the EduTech organisations powering Africa's classrooms with platforms, AI and innovation.",
    faqs: buildStandardFaqs({
      eligibility: "EduTech organisations with verifiable African user base in 1+ markets.",
      whoCanNominate: "Anyone, subject to NRC verification.",
      evidence: "Product description, user metrics, learning outcomes, partner attestations.",
      publicVoting: "Yes — Blue Garnet competitive track.",
      review: "NRC verification, jury shortlist, then public vote + jury final score.",
    }),
    legacyComponentKey: "EduTechAfrica",
    mergedFrom: ["/categories/edutech-africa", "/category/edutech-africa"],
  },
  {
    slug: "stem-education-africa",
    finalName: "Best STEM Education Champion (Africa)",
    group: G,
    url: url("stem-education-africa"),
    parentPage: PARENT,
    shortDescription:
      "Recognising organisations and programmes advancing STEM learning, research and innovation across Africa.",
    eligibilitySummary: "Programmes, schools or organisations delivering STEM-focused education in Africa.",
    whoCanBeNominated: "Schools, NGOs, programmes, or companies with documented STEM education delivery.",
    whoCanNominate: "Anyone, subject to NRC verification.",
    requiredEvidence: [
      "Programme overview and curriculum",
      "Learner numbers and outcomes",
      "Partner or institutional endorsement",
      "Innovation or research outputs (where applicable)",
    ],
    reviewMethod: "NRC eligibility → jury shortlist → public vote → final score.",
    votingRole: "Public voting — Blue Garnet weighted.",
    judgingRole: "Jury shortlist and final scoring.",
    relatedCategories: ["edutech-africa", "ngo-education-africa", "rd-nigeria"],
    seoTitle: "Best STEM Education Champion (Africa) | NESA-Africa 2026",
    metaDescription:
      "Vote and nominate the African STEM champions advancing science, technology, engineering and maths education.",
    faqs: buildStandardFaqs({
      eligibility: "Schools, NGOs, programmes or companies delivering STEM education in Africa.",
      whoCanNominate: "Anyone, subject to NRC verification.",
      evidence: "Programme overview, learner data, partner endorsements, research outputs.",
      publicVoting: "Yes — Blue Garnet competitive track.",
      review: "NRC verification, jury shortlist, then public vote + jury final score.",
    }),
    legacyComponentKey: "STEMEducationAfrica",
    mergedFrom: ["/categories/stem-africa", "/category/stem-education-africa"],
  },
  {
    slug: "media-advocacy-nigeria",
    finalName: "Best Media in Educational Advocacy (Nigeria)",
    group: G,
    url: url("media-advocacy-nigeria"),
    parentPage: PARENT,
    shortDescription:
      "Honouring Nigerian media houses, programmes and journalists driving sustained advocacy for education.",
    eligibilitySummary: "Nigerian media outlets, programmes or journalists with sustained education advocacy.",
    whoCanBeNominated: "Newsrooms, broadcast programmes, podcasts, online publications and journalists.",
    whoCanNominate: "Anyone — public, peers, audiences, education stakeholders.",
    requiredEvidence: [
      "Body of work links (articles, episodes, broadcasts)",
      "Reach or audience metrics",
      "Policy or outcome influence evidence",
      "Editorial independence statement",
    ],
    reviewMethod: "NRC eligibility → jury shortlist → public vote → final score.",
    votingRole: "Public voting — Blue Garnet weighted.",
    judgingRole: "Jury shortlist and final scoring.",
    relatedCategories: ["creative-arts-nigeria", "ngo-education-nigeria", "csr-education-nigeria"],
    seoTitle: "Best Media in Educational Advocacy (Nigeria) | NESA-Africa 2026",
    metaDescription:
      "Vote and nominate the Nigerian media driving consistent, evidence-based advocacy for education.",
    faqs: buildStandardFaqs({
      eligibility: "Nigerian media outlets, programmes or journalists with sustained education advocacy.",
      whoCanNominate: "Anyone, subject to NRC verification.",
      evidence: "Body of work links, audience metrics, influence evidence, editorial independence.",
      publicVoting: "Yes — Blue Garnet competitive track.",
      review: "NRC verification, jury shortlist, then public vote + jury final score.",
    }),
    legacyComponentKey: "MediaAdvocacyNigeria",
    mergedFrom: ["/categories/media-nigeria", "/category/media-advocacy-nigeria"],
  },
  {
    slug: "creative-arts-nigeria",
    finalName: "Creative Arts Education Impact (Nigeria)",
    group: G,
    url: url("creative-arts-nigeria"),
    parentPage: PARENT,
    shortDescription:
      "Celebrating creative arts initiatives delivering education impact for Nigerian learners.",
    eligibilitySummary: "Creative arts organisations, programmes or collectives delivering education in Nigeria.",
    whoCanBeNominated: "Arts collectives, foundations, programmes, schools, festivals and creative platforms.",
    whoCanNominate: "Anyone, subject to NRC verification.",
    requiredEvidence: [
      "Programme overview",
      "Learner or participant data",
      "Partner endorsements",
      "Outputs portfolio",
    ],
    reviewMethod: "NRC eligibility → jury shortlist → public vote → final score.",
    votingRole: "Public voting — Blue Garnet weighted.",
    judgingRole: "Jury shortlist and final scoring.",
    relatedCategories: ["media-advocacy-nigeria", "ngo-education-nigeria"],
    seoTitle: "Creative Arts Education Impact (Nigeria) | NESA-Africa 2026",
    metaDescription:
      "Vote and nominate the Nigerian creative-arts initiatives delivering measurable education impact.",
    faqs: buildStandardFaqs({
      eligibility: "Creative-arts organisations, programmes or collectives delivering education in Nigeria.",
      whoCanNominate: "Anyone, subject to NRC verification.",
      evidence: "Programme overview, participant data, partner endorsements, outputs portfolio.",
      publicVoting: "Yes — Blue Garnet competitive track.",
      review: "NRC verification, jury shortlist, then public vote + jury final score.",
    }),
    legacyComponentKey: "CreativeArtsNigeria",
    mergedFrom: ["/categories/creative-arts-nigeria", "/category/creative-arts-nigeria"],
  },
  {
    slug: "education-state-nigeria",
    finalName: "Best Education-Friendly State (Nigeria)",
    group: G,
    url: url("education-state-nigeria"),
    parentPage: PARENT,
    shortDescription:
      "Celebrating Nigerian states making the boldest investments and reforms in basic and tertiary education.",
    eligibilitySummary:
      "Any of Nigeria's 36 states + FCT with documented education reform, investment or measurable enrolment/outcome improvements.",
    whoCanBeNominated: "State governments (basic + tertiary education ministries).",
    whoCanNominate: "Public, civic groups, education stakeholders, or self-nomination by state.",
    requiredEvidence: [
      "Budget allocation evidence",
      "Reform documentation",
      "Enrolment / outcome data with citations",
      "Independent third-party verification (e.g., media, civic society)",
    ],
    reviewMethod: "NRC eligibility → jury shortlist → public vote → final score.",
    votingRole: "Public voting — Blue Garnet weighted.",
    judgingRole: "Jury shortlist and final scoring with policy-expert panel.",
    relatedCategories: ["political-leaders-nigeria", "csr-education-nigeria"],
    seoTitle: "Best Education-Friendly State (Nigeria) | NESA-Africa 2026",
    metaDescription: "Vote and nominate the Nigerian states leading the boldest reforms in education.",
    faqs: buildStandardFaqs({
      eligibility: "Any of Nigeria's 36 states + FCT with documented education reform or investment.",
      whoCanNominate: "Public, civic groups, education stakeholders, or self-nomination by the state.",
      evidence: "Budget evidence, reform documentation, enrolment/outcome data with citations, independent verification.",
      publicVoting: "Yes — Blue Garnet competitive track.",
      review: "NRC verification, jury shortlist (policy experts), then public vote + jury final score.",
    }),
    legacyComponentKey: "EducationFriendlyStateNigeria",
    mergedFrom: ["/categories/education-state-nigeria", "/category/education-friendly-state-nigeria"],
  },
];
