
-- Stage 4 seed: categories from architecture
WITH cyc AS (SELECT id FROM public.recognition_cycles WHERE slug='nesa-africa-2026'),
input(tier_slug, slug, name, tagline, sort_order) AS (VALUES
  ('africa-education-icon', 'icon-of-the-decade', 'Africa Education Icon of the Decade', 'Three lifetime subcategories across Africa, Diaspora and Friends of Africa.', 0),
  ('gold-blue-garnet', 'csr-for-education', 'CSR for Education by Organisations', 'Corporate citizenship advancing African education.', 0),
  ('gold-blue-garnet', 'education-philanthropy', 'Education Philanthropy', 'Philanthropists and foundations funding learning.', 1),
  ('gold-blue-garnet', 'institutional-and-bilateral-grants', 'Institutional & Bilateral Grants', 'Multilateral and bilateral funding for education.', 2),
  ('gold-blue-garnet', 'faith-based-organisations', 'Faith-Based Organisations Advancing Education', 'Religious institutions building schools and scholarships.', 3),
  ('gold-blue-garnet', 'ngos-advancing-education', 'NGOs Advancing Education', 'Civil society organisations transforming learning.', 4),
  ('gold-blue-garnet', 'education-policy-and-government', 'Education Policy & Government Leadership', 'Public officials driving systemic reform.', 5),
  ('gold-blue-garnet', 'universities-and-higher-education', 'Universities & Higher Education', 'Continental excellence in tertiary education.', 6),
  ('gold-blue-garnet', 'tvet-and-technical-education', 'TVET & Technical Education', 'Skills, trade and technical training leaders.', 7),
  ('gold-blue-garnet', 'edtech-and-ai-innovation', 'EdTech & AI Innovation', 'Technology and AI advancing classrooms.', 8),
  ('gold-blue-garnet', 'stem-education', 'STEM Education', 'Science, technology, engineering and mathematics champions.', 9),
  ('gold-blue-garnet', 'libraries-and-knowledge-systems', 'Libraries & Knowledge Systems', 'Custodians of African knowledge.', 10),
  ('gold-blue-garnet', 'research-and-curriculum-development', 'Research & Curriculum Development', 'Researchers and curriculum architects.', 11),
  ('gold-blue-garnet', 'media-and-journalism-for-education', 'Media & Journalism for Education', 'Editorial voices amplifying education.', 12),
  ('gold-blue-garnet', 'inclusive-and-special-needs-education', 'Inclusive & Special Needs Education', 'Accessible, inclusive learning for every child.', 13),
  ('gold-blue-garnet', 'early-childhood-education', 'Early Childhood Education', 'Foundations of lifelong learning.', 14),
  ('gold-blue-garnet', 'school-transformation', 'School Transformation', 'Schools reinvented through bold leadership.', 15),
  ('gold-blue-garnet', 'skills-development-and-employability', 'Skills Development & Employability', 'Bridging learning and the world of work.', 16),
  ('gold-blue-garnet', 'regional-education-leadership', 'Regional Education Leadership', 'Honouring leaders across each African region.', 17),
  ('platinum', 'international-bilateral-education-partners', 'International Bilateral Education Partners', 'Bilateral partners enabling African education.', 0),
  ('platinum', 'embassies-supporting-african-education', 'Embassies Supporting African Education', 'Diplomatic missions advancing learning.', 1),
  ('platinum', 'development-partners', 'Development Partners', 'Multilateral development institutions.', 2),
  ('platinum', 'un-agencies', 'UN Agencies', 'United Nations agencies enabling education.', 3),
  ('platinum', 'foundations', 'Foundations', 'Private and public foundations.', 4),
  ('platinum', 'religious-organisations', 'Religious Organisations', 'Faith-based institutional impact.', 5),
  ('platinum', 'corporate-foundations', 'Corporate Foundations', 'Corporate philanthropy at scale.', 6),
  ('platinum', 'universities', 'Universities', 'Higher-education institutional leadership.', 7),
  ('platinum', 'research-institutions', 'Research Institutions', 'Institutions advancing African scholarship.', 8),
  ('platinum', 'national-libraries', 'National Libraries', 'Custodians of national knowledge.', 9),
  ('platinum', 'government-ministries', 'Government Ministries', 'Ministries leading education reform.', 10),
  ('platinum', 'education-agencies', 'Education Agencies', 'Statutory and regulatory bodies.', 11),
  ('platinum', 'csr-coalitions', 'CSR Coalitions', 'Cross-sector CSR alliances.', 12),
  ('platinum', 'education-networks', 'Education Networks', 'Continental education networks.', 13),
  ('platinum', 'professional-associations', 'Professional Associations', 'Educators and professional bodies.', 14),
  ('platinum', 'international-ngos', 'International NGOs', 'Global NGOs serving African education.', 15),
  ('platinum', 'african-regional-organisations', 'African Regional Organisations', 'AU, RECs and regional bodies.', 16),
  ('platinum', 'diaspora-organisations', 'Diaspora Organisations', 'African diaspora networks.', 17),
  ('platinum', 'friends-of-africa-organisations', 'Friends of Africa Organisations', 'Global allies enabling African education.', 18),
  ('platinum', 'special-recognition', 'Special Recognition', 'Honourable institutional citations.', 19),
  ('platinum', 'legacy-recognition', 'Legacy Recognition', 'Long-form institutional legacy.', 20),
  ('influencer-impact', 'social-media', 'Social Media Education Champions', 'Creators advancing learning across digital platforms.', 0),
  ('influencer-impact', 'sports', 'Sports Icons Supporting Education', 'Athletes using their platform for African education.', 1),
  ('influencer-impact', 'music', 'Music Icons Supporting Education', 'Musicians championing learning, advocacy and access.', 2)
)
INSERT INTO public.recognition_categories (tier_id, slug, name, tagline, sort_order)
SELECT t.id, i.slug, i.name, i.tagline, i.sort_order
FROM input i JOIN public.recognition_tiers t ON t.slug = i.tier_slug
JOIN cyc ON t.cycle_id = cyc.id
ON CONFLICT (tier_id, slug) DO UPDATE SET name=EXCLUDED.name, tagline=EXCLUDED.tagline, sort_order=EXCLUDED.sort_order;

-- Ensure derived registry parent slugs exist under Gold-Blue Garnet
WITH cyc AS (SELECT id FROM public.recognition_cycles WHERE slug='nesa-africa-2026'),
tier AS (SELECT t.id FROM public.recognition_tiers t JOIN cyc ON t.cycle_id=cyc.id WHERE t.slug='gold-blue-garnet'),
extras(slug, name, tagline) AS (VALUES
  ('edutech-innovation', 'EduTech Innovation', 'EdTech startups and initiatives scaling African learning.'),
  ('media-advocacy', 'Media for Education Advocacy', 'Print, radio, television and digital media championing education.'),
  ('ngo-advancement', 'NGOs Advancing Education (Registry)', 'Registry-derived NGO subcategories for Nigeria and Africa.'),
  ('stem-programme', 'STEM Education Programmes', 'Programme-level STEM excellence, inclusion and outreach.'),
  ('creative-arts', 'Creative Arts for Education', 'Film, music, literature and performing arts advancing learning.'),
  ('education-friendly-state', 'Education-Friendly States', 'State-level policy and implementation excellence.'),
  ('tertiary-library', 'Tertiary Institution Libraries', 'University, polytechnic, college of education and nursing libraries.'),
  ('research-excellence', 'Research Excellence', 'Agricultural, pharmaceutical and environmental research institutes.'),
  ('christian-education-impact', 'Christian Education Impact', 'Christian-led education infrastructure, scholarships and advocacy.'),
  ('islamic-education-impact', 'Islamic Education Impact', 'Islamic-led education infrastructure, scholarships and advocacy.'),
  ('political-leadership', 'Political Leadership for Education', 'Political leaders driving scholarships, infrastructure and advocacy.'),
  ('international-partnership', 'International Partnership for Education', 'Embassies, bilateral orgs, INGOs and grant-givers.'),
  ('diaspora-impact', 'Diaspora Education Impact', 'Diaspora-led partnerships, philanthropy and innovation.'),
  ('influencers-education-impact', 'Influencer Education Impact (Registry)', 'Registry-derived influencer subcategories.')
)
INSERT INTO public.recognition_categories (tier_id, slug, name, tagline, sort_order)
SELECT (SELECT id FROM tier), e.slug, e.name, e.tagline, 100
FROM extras e
ON CONFLICT (tier_id, slug) DO NOTHING;

-- Subcategories
WITH input(cat_slug, slug, name, description, sort_order) AS (VALUES
  ('icon-of-the-decade', 'africa-education-philanthropy-icon-of-the-decade', 'Africa Education Philanthropy Icon of the Decade', NULL, 0),
  ('icon-of-the-decade', 'literary-and-new-curriculum-advocate-icon-of-the-decade', 'Literary & New Curriculum Advocate Icon of the Decade', NULL, 1),
  ('icon-of-the-decade', 'africa-technical-educator-icon-of-the-decade', 'Africa Technical Educator Icon of the Decade', NULL, 2),
  ('csr-for-education', 'banking-finance-csr', 'Best CSR for Education – Banking & Finance', 'Banks and financial institutions driving education across Africa.', 3),
  ('csr-for-education', 'telecommunications-csr', 'Best CSR for Education – Telecommunications', 'Telecom companies connecting schools and enabling digital literacy.', 4),
  ('csr-for-education', 'oil-gas-csr', 'Best CSR for Education – Oil & Gas', 'Oil and gas companies investing in host-community education.', 5),
  ('csr-for-education', 'food-beverages-csr', 'Best CSR for Education – Food & Beverages', 'Food and beverage companies supporting school feeding and learning.', 6),
  ('csr-for-education', 'aviation-csr', 'Best CSR for Education – Aviation', 'Airlines providing scholarships and STEM education.', 7),
  ('csr-for-education', 'manufacturing-csr', 'Best CSR for Education – Manufacturing', 'Manufacturers investing in TVET and STEM.', 8),
  ('csr-for-education', 'fintech-csr', 'Best CSR for Education – FinTech', 'FinTechs advancing financial literacy and digital education.', 9),
  ('csr-for-education', 'insurance-csr', 'Best CSR for Education – Insurance', 'Insurers supporting scholarships and infrastructure.', 10),
  ('csr-for-education', 'real-estate-construction-csr', 'Best CSR for Education – Real Estate & Construction', 'Building and renovating educational facilities.', 11),
  ('csr-for-education', 'retail-ecommerce-csr', 'Best CSR for Education – Retail & E-Commerce', 'Supporting libraries, scholarships and community education.', 12),
  ('csr-for-education', 'pharmaceuticals-csr', 'Best CSR for Education – Pharmaceuticals', 'Advancing health education and STEM in schools.', 13),
  ('csr-for-education', 'conglomerates-csr', 'Best CSR for Education – Conglomerates', 'Multi-sector education contributions across Africa.', 14),
  ('csr-for-education', 'media-entertainment-csr', 'Best CSR for Education – Media & Entertainment', 'Producing educational content and supporting learning.', 15),
  ('csr-for-education', 'agriculture-agribusiness-csr', 'Best CSR for Education – Agriculture & Agribusiness', 'Agricultural education and rural skills development.', 16),
  ('csr-for-education', 'healthcare-hospitals-csr', 'Best CSR for Education – Health Care & Hospitals', 'Health education and science laboratories in schools.', 17),
  ('csr-for-education', 'professional-services-csr', 'Best CSR for Education – Professional Services', 'Mentorship, career guidance and educational support.', 18),
  ('csr-for-education', 'microfinance-banks-csr', 'Best CSR for Education – Microfinance Banks', 'Loans, scholarships and financial literacy programmes.', 19),
  ('csr-for-education', 'emerging-telecommunications-csr', 'Best CSR for Education – Emerging Telecommunications', 'Expanding internet access and digital learning.', 20),
  ('csr-for-education', 'technology-software-csr', 'Best CSR for Education – Technology & Software', 'Digital tools, teacher training and platforms.', 21),
  ('csr-for-education', 'real-estate-development-csr', 'Best CSR for Education – Real Estate Development', 'Constructing schools and educational facilities.', 22),
  ('csr-for-education', 'commercial-retail-csr', 'Best CSR for Education – Commercial Retail', 'School supplies, libraries and educational programmes.', 23),
  ('csr-for-education', 'hotel-csr', 'Best CSR for Education – Hotels', 'Hospitality-led scholarships and community programmes.', 24),
  ('csr-for-education', 'emerging-technology-csr', 'Best CSR for Education – Emerging Technology', 'New technology supporting African education innovation.', 25),
  ('edutech-innovation', 'edutech-startup', 'Best EduTech Innovation – Startup', 'Innovative early-stage EdTech startups.', 26),
  ('edutech-innovation', 'established-edutech', 'Best EduTech Innovation – Established Company', 'Mature EdTech companies scaling digital learning.', 27),
  ('edutech-innovation', 'social-impact-edutech', 'Best EduTech Innovation – Social Impact Initiative', 'Non-profit and hybrid EdTech focused on equity.', 28),
  ('media-advocacy', 'print-media-advocacy', 'Best Media Organisation for Education Advocacy – Print Media', 'Print publications driving education advocacy.', 29),
  ('media-advocacy', 'radio-education-advocacy', 'Best Media Organisation for Education Advocacy – Radio Programme', 'Radio amplifying education stories.', 30),
  ('media-advocacy', 'television-education-advocacy', 'Best Media Organisation for Education Advocacy – Television Content', 'Television networks producing education programming.', 31),
  ('media-advocacy', 'digital-media-advocacy', 'Best Media Organisation for Education Advocacy – Digital Media', 'Digital outlets transforming education conversation.', 32),
  ('ngo-advancement', 'ngo-infrastructure-nigeria', 'Best NGO for Education – Infrastructure (Nigeria)', 'NGOs building and equipping Nigerian schools.', 33),
  ('ngo-advancement', 'ngo-educational-materials-nigeria', 'Best NGO for Education – Educational Materials (Nigeria)', 'NGOs providing books, devices and materials.', 34),
  ('ngo-advancement', 'ngo-education-aid-scholarships-nigeria', 'Best NGO for Education – Education Aid & Scholarships (Nigeria)', 'Scholarships and financial support in Nigeria.', 35),
  ('ngo-advancement', 'youth-empowerment-ngo', 'Best NGO for Education – Youth Empowerment (Nigeria)', 'Skills, leadership and entrepreneurship for youth.', 36),
  ('ngo-advancement', 'women-girls-education-ngo', 'Best NGO for Education – Women & Girls (Nigeria)', 'Advancing girls'' education and empowerment.', 37),
  ('ngo-advancement', 'ngo-infrastructure-africa', 'Best NGO for Education – Infrastructure (Africa)', 'Building and rehabilitating schools across Africa.', 38),
  ('ngo-advancement', 'ngo-education-aid-africa', 'Best NGO for Education – Education Aid (Africa)', 'Direct education aid and emergency learning support.', 39),
  ('ngo-advancement', 'ngo-educational-materials-africa', 'Best NGO for Education – Educational Materials (Africa)', 'Distributing learning resources continent-wide.', 40),
  ('ngo-advancement', 'ngo-youth-skills-africa', 'Best NGO for Education – Youth Skills (Africa)', 'Vocational and skills training for African youth.', 41),
  ('ngo-advancement', 'ngo-women-girls-advocacy-africa', 'Best NGO for Education – Women & Girls Advocacy (Africa)', 'Advocating for girls'' education continent-wide.', 42),
  ('stem-programme', 'inclusive-stem', 'Best STEM Education Programme – Inclusive STEM', 'Access for all learners including marginalised communities.', 43),
  ('stem-programme', 'digital-stem-innovation', 'Best STEM Education Programme – Digital Innovation', 'Coding, robotics and digital tools transforming STEM.', 44),
  ('stem-programme', 'community-stem-outreach', 'Best STEM Education Programme – Community Outreach', 'Rural and out-of-school STEM outreach.', 45),
  ('stem-programme', 'girls-in-stem', 'Best STEM Education Programme – Girls in STEM', 'Increasing girls'' participation in STEM.', 46),
  ('creative-arts', 'nollywood-educational-content', 'Best Creative Arts – Nollywood Educational Content', 'Films and series that educate and inspire.', 47),
  ('creative-arts', 'music-industry-education', 'Best Creative Arts – Music Industry Contribution', 'Music promoting education campaigns.', 48),
  ('creative-arts', 'literature-artistic-works-education', 'Best Creative Arts – Literature & Artistic Works', 'Writers and artists advancing education.', 49),
  ('creative-arts', 'visual-arts-education-impact', 'Best Creative Arts – Visual Arts Impact', 'Visual artists promoting education.', 50),
  ('creative-arts', 'performing-arts-education', 'Best Creative Arts – Performing Arts', 'Theatre and dance for community education.', 51),
  ('creative-arts', 'film-media-education', 'Best Creative Arts – Film & Media', 'Documentaries and educational media.', 52),
  ('creative-arts', 'creative-advocacy-education', 'Best Creative Arts – Creative Advocacy Campaigns', 'Art, music and media advocating for education.', 53),
  ('education-friendly-state', 'north-central-education-state', 'Best Education Policy & Implementation State – North Central', 'North Central state with measurable outcomes.', 54),
  ('education-friendly-state', 'north-east-education-state', 'Best Education Policy & Implementation State – North East', 'North East state with measurable outcomes.', 55),
  ('education-friendly-state', 'north-west-education-state', 'Best Education Policy & Implementation State – North West', 'North West state with measurable outcomes.', 56),
  ('education-friendly-state', 'south-east-education-state', 'Best Education Policy & Implementation State – South East', 'South East state with measurable outcomes.', 57),
  ('education-friendly-state', 'south-south-education-state', 'Best Education Policy & Implementation State – South South', 'South South state with measurable outcomes.', 58),
  ('education-friendly-state', 'south-west-education-state', 'Best Education Policy & Implementation State – South West', 'South West state with measurable outcomes.', 59),
  ('tertiary-library', 'university-library-public', 'Best Public University Library', 'Excellent public university library.', 60),
  ('tertiary-library', 'university-library-private', 'Best Private University Library', 'Excellent private university library.', 61),
  ('tertiary-library', 'polytechnic-library-public', 'Best Public Polytechnic Library', 'Public polytechnic library.', 62),
  ('tertiary-library', 'polytechnic-library-private', 'Best Private Polytechnic Library', 'Private polytechnic library.', 63),
  ('tertiary-library', 'college-of-education-library-public', 'Best Public College of Education Library', 'Public college of education library.', 64),
  ('tertiary-library', 'college-of-education-library-private', 'Best Private College of Education Library', 'Private college of education library.', 65),
  ('tertiary-library', 'college-of-nursing-library-public', 'Best Public College of Nursing Library', 'Public college of nursing library.', 66),
  ('tertiary-library', 'college-of-nursing-library-private', 'Best Private College of Nursing Library', 'Private college of nursing library.', 67),
  ('research-excellence', 'agricultural-research-institute', 'Best Agricultural Research Institute', 'Agricultural research institute.', 68),
  ('research-excellence', 'pharmaceutical-research-institute', 'Best Pharmaceutical & Drug Research Institute', 'Pharmaceutical research institute.', 69),
  ('research-excellence', 'environmental-research-institute', 'Best Environmental & Ecological Research Institute', 'Environmental research institute.', 70),
  ('christian-education-impact', 'christian-education-infrastructure', 'Christian Education – Educational Infrastructure Development', 'Christian orgs building schools.', 71),
  ('christian-education-impact', 'christian-scholarship-program', 'Christian Education – Scholarship Program', 'Christian scholarship programmes.', 72),
  ('christian-education-impact', 'christian-holistic-support', 'Christian Education – Holistic Educational Support', 'Holistic Christian educational support.', 73),
  ('christian-education-impact', 'christian-education-advocacy', 'Christian Education – Advocacy for Reforms & Awareness Campaigns', 'Christian-led education advocacy.', 74),
  ('islamic-education-impact', 'islamic-education-infrastructure', 'Islamic Education – Educational Infrastructure Development', 'Islamic orgs building schools.', 75),
  ('islamic-education-impact', 'islamic-scholarship-program', 'Islamic Education – Scholarship Program', 'Islamic scholarship programmes.', 76),
  ('islamic-education-impact', 'islamic-holistic-support', 'Islamic Education – Holistic Educational Support', 'Holistic Islamic educational support.', 77),
  ('islamic-education-impact', 'islamic-education-advocacy', 'Islamic Education – Advocacy for Reforms & Awareness Campaigns', 'Islamic-led education advocacy.', 78),
  ('political-leadership', 'political-scholarship-program', 'Political Leadership – Outstanding Scholarship Program', 'Political leaders running scholarships.', 79),
  ('political-leadership', 'political-infrastructure-development', 'Political Leadership – Infrastructure Development & Donations', 'Political infrastructure donations.', 80),
  ('political-leadership', 'political-education-advocacy', 'Political Leadership – Advocacy & Policy Development', 'Political advocacy and policy.', 81),
  ('international-partnership', 'international-embassy-contribution', 'Best International Embassy Contribution to Education', 'Embassies funding scholarships.', 82),
  ('international-partnership', 'bilateral-education-support', 'Best Bilateral Organization Education Support', 'Bilateral organisations supporting education.', 83),
  ('international-partnership', 'international-ngo-education', 'Best International NGO Education Support', 'International NGOs delivering outcomes.', 84),
  ('international-partnership', 'global-education-grant', 'Best Educational Grant-Giving Organization', 'Global grant-giving organisations.', 85),
  ('international-partnership', 'international-airline-education', 'Best International Airline Education Support', 'International airlines supporting education.', 86),
  ('international-partnership', 'international-leadership-training', 'Best International Leadership/Training Organization', 'International leadership training orgs.', 87),
  ('diaspora-impact', 'diaspora-association-partnership', 'Diaspora Association Educational Partnership', 'Diaspora associations partnering with schools.', 88),
  ('diaspora-impact', 'outstanding-diaspora-champion', 'Outstanding Individual Diaspora Education Champion', 'Individual diaspora champions.', 89),
  ('diaspora-impact', 'diaspora-institutional-development', 'Diaspora-Led Institutional Development & Capacity-Building', 'Diaspora-led institution building.', 90),
  ('diaspora-impact', 'diaspora-philanthropy-csr', 'Diaspora Philanthropy & CSR Impact', 'Diaspora philanthropy and CSR impact.', 91),
  ('diaspora-impact', 'diaspora-digital-innovation', 'Diaspora Digital Education Innovation', 'Diaspora digital innovation for education.', 92),
  ('influencers-education-impact', 'social-media-education-influencers', 'African Social Media Influencers Education Impact Award', 'Social media creators advancing education.', 93),
  ('influencers-education-impact', 'sports-icons-education', 'African Sports Icons Supporting Education', 'Athletes supporting education.', 94),
  ('influencers-education-impact', 'music-icons-education', 'African Music Icons Supporting Education', 'Musicians supporting education.', 95)
)
INSERT INTO public.recognition_subcategories (category_id, slug, name, description, sort_order)
SELECT c.id, i.slug, i.name, i.description, i.sort_order
FROM input i JOIN public.recognition_categories c ON c.slug = i.cat_slug
ON CONFLICT (category_id, slug) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, sort_order=EXCLUDED.sort_order;
