// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getMissingPublicEnvVars } from '@/config/runtimeEnv';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const missingPublicEnvVars = getMissingPublicEnvVars();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (missingPublicEnvVars.length > 0) {
  throw new Error(
    `Missing required public env vars: ${missingPublicEnvVars.join(", ")}. ` +
      "Set them in your local .env file and in your hosting provider's environment settings."
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
